# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/per/GPIO_LED/GPIO_LED.srcs/sources_1/bd/gpio_led/ip/gpio_led_auto_pc_0/gpio_led_auto_pc_0.xci
# IP: The module: 'gpio_led_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/per/GPIO_LED/GPIO_LED.gen/sources_1/bd/gpio_led/ip/gpio_led_auto_pc_0/gpio_led_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_led_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/per/GPIO_LED/GPIO_LED.srcs/sources_1/bd/gpio_led/ip/gpio_led_auto_pc_0/gpio_led_auto_pc_0.xci
# IP: The module: 'gpio_led_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/per/GPIO_LED/GPIO_LED.gen/sources_1/bd/gpio_led/ip/gpio_led_auto_pc_0/gpio_led_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_led_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
