-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lc3 is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 9;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of lc3 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "lc3_lc3,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.154000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=64,HLS_SYN_DSP=0,HLS_SYN_FF=877,HLS_SYN_LUT=2034,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (37 downto 0) := "00000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (37 downto 0) := "00000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (37 downto 0) := "00000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (37 downto 0) := "00000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (37 downto 0) := "00000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (37 downto 0) := "00000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (37 downto 0) := "00001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (37 downto 0) := "00010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (37 downto 0) := "00100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (37 downto 0) := "01000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (37 downto 0) := "10000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_1_2 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_1_3 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_1_4 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_1_5 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_1_6 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_1_7 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal IR : STD_LOGIC_VECTOR (15 downto 0);
    signal PC : STD_LOGIC_VECTOR (15 downto 0);
    signal PC_out_ap_vld : STD_LOGIC;
    signal R0_ap_vld : STD_LOGIC;
    signal R1_ap_vld : STD_LOGIC;
    signal R2_ap_vld : STD_LOGIC;
    signal R3_ap_vld : STD_LOGIC;
    signal R4_ap_vld : STD_LOGIC;
    signal R5_ap_vld : STD_LOGIC;
    signal R6_ap_vld : STD_LOGIC;
    signal R7_ap_vld : STD_LOGIC;
    signal N : STD_LOGIC_VECTOR (15 downto 0);
    signal N_ap_vld : STD_LOGIC;
    signal Z : STD_LOGIC_VECTOR (15 downto 0);
    signal Z_ap_vld : STD_LOGIC;
    signal P : STD_LOGIC_VECTOR (15 downto 0);
    signal P_ap_vld : STD_LOGIC;
    signal n1 : STD_LOGIC_VECTOR (15 downto 0);
    signal n1_ap_vld : STD_LOGIC;
    signal p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p1_ap_vld : STD_LOGIC;
    signal z1 : STD_LOGIC_VECTOR (15 downto 0);
    signal z1_ap_vld : STD_LOGIC;
    signal reg_r_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal reg_r_ce0 : STD_LOGIC;
    signal reg_r_we0 : STD_LOGIC;
    signal reg_r_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_r_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_r_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal reg_r_ce1 : STD_LOGIC;
    signal reg_r_we1 : STD_LOGIC;
    signal reg_r_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_r_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal z_r : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal n_r : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal p_r : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal memory_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal memory_ce0 : STD_LOGIC;
    signal memory_we0 : STD_LOGIC;
    signal memory_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal memory_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_807_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_855 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln_fu_905_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal reg_861 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state35 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state35 : signal is "none";
    signal reg_868 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_829_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal reg_875 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal trunc_ln_reg_1640 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_838_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_879 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state31 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state31 : signal is "none";
    signal PC_read_reg_1589 : STD_LOGIC_VECTOR (15 downto 0);
    signal IR_read_reg_1602 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1_1_fu_885_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln1_1_reg_1613 : STD_LOGIC_VECTOR (10 downto 0);
    signal pc_offset6_fu_889_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal pc_offset6_reg_1618 : STD_LOGIC_VECTOR (5 downto 0);
    signal pc_offset9_fu_897_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal pc_offset9_reg_1624 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln1_5_fu_901_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln1_5_reg_1634 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_813_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_1677 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_4_reg_1683 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1689 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln272_fu_1036_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_820_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln17_reg_1700 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln272_1_fu_1044_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal add_ln225_fu_1066_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln225_reg_1728 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal add_ln214_reg_1738 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal add_ln207_reg_1754 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal add_ln186_reg_1765 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal icmp_ln195_fu_1157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal xor_ln195_fu_1169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln168_fu_1196_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln168_reg_1784 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal add_ln164_reg_1804 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal grp_fu_843_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_reg_1809 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_1813 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln148_reg_1819 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln152_reg_1823 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1_1_fu_1338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1_1_reg_1829 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal icmp_ln131_reg_1841 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal xor_ln131_fu_1385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal ap_CS_fsm_state27 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state27 : signal is "none";
    signal add_ln101_reg_1857 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal icmp_ln110_fu_1413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln110_fu_1425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln80_fu_1472_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln80_reg_1875 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state30 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state30 : signal is "none";
    signal add_ln52_fu_1502_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln52_reg_1881 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln89_fu_1514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln89_fu_1525_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_fu_1542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln61_fu_1553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal reg_load_14_reg_1913 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state36 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state36 : signal is "none";
    signal reg_load_15_reg_1918 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_load_16_reg_1923 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state37 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state37 : signal is "none";
    signal reg_load_17_reg_1928 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge9_reg_547 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln191_fu_1151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge7_reg_558 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln174_fu_1263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_storemerge14_phi_fu_573_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge14_reg_569 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_storemerge12_phi_fu_584_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge12_reg_580 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln152_fu_1287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_storemerge19_phi_fu_595_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge19_reg_591 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_storemerge17_phi_fu_606_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge17_reg_602 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge24_reg_613 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge22_reg_624 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge30_reg_635 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_fu_1407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge28_reg_646 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge36_reg_657 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_fu_1509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge34_reg_668 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge43_reg_679 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln57_fu_1537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge41_reg_690 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln272_reg_701 : STD_LOGIC_VECTOR (15 downto 0);
    signal PC_assign_10_reg_749 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_CS_fsm_state29 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state29 : signal is "none";
    signal ap_CS_fsm_state32 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state32 : signal is "none";
    signal ap_CS_fsm_state33 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state33 : signal is "none";
    signal ap_phi_mux_storemerge_phi_fu_788_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state38 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state38 : signal is "none";
    signal zext_ln225_1_fu_915_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln168_fu_920_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln80_fu_925_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln83_fu_930_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln52_fu_935_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_fu_940_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln240_fu_1049_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln230_fu_1053_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_fu_1061_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln225_2_fu_1072_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal zext_ln217_fu_1079_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln217_2_fu_1099_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln217_fu_1104_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln210_fu_1109_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln210_2_fu_1132_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln189_fu_1146_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln146_2_fu_1221_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln168_2_fu_1226_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln146_fu_1230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln168_1_fu_1235_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln146_fu_1246_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln125_2_fu_1363_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln125_fu_1368_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln104_fu_1390_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln104_1_fu_1402_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln80_1_fu_1459_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln52_1_fu_1489_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln189_fu_1140_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln104_fu_1395_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state34 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state34 : signal is "none";
    signal grp_fu_797_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln1_3_fu_893_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln248_fu_975_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln249_fu_989_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln250_fu_1003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln251_fu_1013_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln251_1_fu_1019_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln272_fu_1025_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln272_fu_1032_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln237_fu_1041_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln34_1_fu_1058_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln32_3_fu_1076_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln217_fu_1084_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln217_1_fu_1090_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln217_1_fu_1094_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln217_fu_1104_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln32_2_fu_1114_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln210_fu_1117_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln210_1_fu_1123_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln210_1_fu_1127_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln189_1_fu_1137_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln34_fu_1193_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln32_1_fu_1202_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln146_fu_1205_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln146_1_fu_1211_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln146_1_fu_1215_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1_1_fu_1322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1_fu_1317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1_2_fu_1333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1_fu_1327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln32_fu_1344_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln125_fu_1347_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln125_1_fu_1353_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln125_1_fu_1357_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_1452_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln75_fu_1449_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln79_fu_1464_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_1482_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln47_fu_1479_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_fu_1494_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ST_fsm_state36_blk : STD_LOGIC;
    signal ap_ST_fsm_state37_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component lc3_reg_r_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (15 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component lc3_memory_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component lc3_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        IR : OUT STD_LOGIC_VECTOR (15 downto 0);
        PC : OUT STD_LOGIC_VECTOR (15 downto 0);
        PC_out : IN STD_LOGIC_VECTOR (15 downto 0);
        PC_out_ap_vld : IN STD_LOGIC;
        R0 : IN STD_LOGIC_VECTOR (15 downto 0);
        R0_ap_vld : IN STD_LOGIC;
        R1 : IN STD_LOGIC_VECTOR (15 downto 0);
        R1_ap_vld : IN STD_LOGIC;
        R2 : IN STD_LOGIC_VECTOR (15 downto 0);
        R2_ap_vld : IN STD_LOGIC;
        R3 : IN STD_LOGIC_VECTOR (15 downto 0);
        R3_ap_vld : IN STD_LOGIC;
        R4 : IN STD_LOGIC_VECTOR (15 downto 0);
        R4_ap_vld : IN STD_LOGIC;
        R5 : IN STD_LOGIC_VECTOR (15 downto 0);
        R5_ap_vld : IN STD_LOGIC;
        R6 : IN STD_LOGIC_VECTOR (15 downto 0);
        R6_ap_vld : IN STD_LOGIC;
        R7 : IN STD_LOGIC_VECTOR (15 downto 0);
        R7_ap_vld : IN STD_LOGIC;
        N : IN STD_LOGIC_VECTOR (15 downto 0);
        N_ap_vld : IN STD_LOGIC;
        Z : IN STD_LOGIC_VECTOR (15 downto 0);
        Z_ap_vld : IN STD_LOGIC;
        P : IN STD_LOGIC_VECTOR (15 downto 0);
        P_ap_vld : IN STD_LOGIC;
        n1 : IN STD_LOGIC_VECTOR (15 downto 0);
        n1_ap_vld : IN STD_LOGIC;
        p1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p1_ap_vld : IN STD_LOGIC;
        z1 : IN STD_LOGIC_VECTOR (15 downto 0);
        z1_ap_vld : IN STD_LOGIC );
    end component;



begin
    reg_r_U : component lc3_reg_r_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => reg_r_address0,
        ce0 => reg_r_ce0,
        we0 => reg_r_we0,
        d0 => reg_r_d0,
        q0 => reg_r_q0,
        address1 => reg_r_address1,
        ce1 => reg_r_ce1,
        we1 => reg_r_we1,
        d1 => reg_r_d1,
        q1 => reg_r_q1);

    memory_U : component lc3_memory_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 65536,
        AddressWidth => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => memory_address0,
        ce0 => memory_ce0,
        we0 => memory_we0,
        d0 => memory_d0,
        q0 => memory_q0);

    control_s_axi_U : component lc3_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        IR => IR,
        PC => PC,
        PC_out => ap_phi_mux_storemerge_phi_fu_788_p4,
        PC_out_ap_vld => PC_out_ap_vld,
        R0 => reg_861,
        R0_ap_vld => R0_ap_vld,
        R1 => reg_868,
        R1_ap_vld => R1_ap_vld,
        R2 => reg_load_14_reg_1913,
        R2_ap_vld => R2_ap_vld,
        R3 => reg_load_15_reg_1918,
        R3_ap_vld => R3_ap_vld,
        R4 => reg_load_16_reg_1923,
        R4_ap_vld => R4_ap_vld,
        R5 => reg_load_17_reg_1928,
        R5_ap_vld => R5_ap_vld,
        R6 => reg_r_q0,
        R6_ap_vld => R6_ap_vld,
        R7 => reg_r_q1,
        R7_ap_vld => R7_ap_vld,
        N => N,
        N_ap_vld => N_ap_vld,
        Z => Z,
        Z_ap_vld => Z_ap_vld,
        P => P,
        P_ap_vld => P_ap_vld,
        n1 => n1,
        n1_ap_vld => n1_ap_vld,
        p1 => p1,
        p1_ap_vld => p1_ap_vld,
        z1 => z1,
        z1_ap_vld => z1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    PC_assign_10_reg_749_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state33) or (ap_const_logic_1 = ap_CS_fsm_state32))) then 
                PC_assign_10_reg_749 <= reg_879;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
                PC_assign_10_reg_749 <= add_ln101_reg_1857;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_2)) or ((ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_A)))) then 
                PC_assign_10_reg_749 <= reg_855;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_6))) then 
                PC_assign_10_reg_749 <= add_ln164_reg_1804;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                PC_assign_10_reg_749 <= add_ln186_reg_1765;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and ((trunc_ln_fu_905_p4 = ap_const_lv4_8) or ((trunc_ln_fu_905_p4 = ap_const_lv4_D) or (trunc_ln_fu_905_p4 = ap_const_lv4_F))))) then 
                PC_assign_10_reg_749 <= PC;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                PC_assign_10_reg_749 <= add_ln207_reg_1754;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                PC_assign_10_reg_749 <= add_ln214_reg_1738;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                PC_assign_10_reg_749 <= grp_fu_838_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_fu_813_p3 = ap_const_lv1_1)))) then 
                PC_assign_10_reg_749 <= PC_read_reg_1589;
            end if; 
        end if;
    end process;

    n_r_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                n_r <= storemerge9_reg_547;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_2))) then 
                n_r <= storemerge24_reg_613;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_A))) then 
                n_r <= ap_phi_mux_storemerge19_phi_fu_595_p4;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_6))) then 
                n_r <= ap_phi_mux_storemerge14_phi_fu_573_p4;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
                n_r <= storemerge30_reg_635;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state32)) then 
                n_r <= storemerge36_reg_657;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state33)) then 
                n_r <= storemerge43_reg_679;
            end if; 
        end if;
    end process;

    p_r_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                p_r <= storemerge7_reg_558;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_2))) then 
                p_r <= storemerge22_reg_624;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_A))) then 
                p_r <= ap_phi_mux_storemerge17_phi_fu_606_p4;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_6))) then 
                p_r <= ap_phi_mux_storemerge12_phi_fu_584_p4;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
                p_r <= storemerge28_reg_646;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state32)) then 
                p_r <= storemerge34_reg_668;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state33)) then 
                p_r <= storemerge41_reg_690;
            end if; 
        end if;
    end process;

    phi_ln272_reg_701_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                phi_ln272_reg_701 <= reg_r_q1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_fu_813_p3 = ap_const_lv1_1))) then 
                phi_ln272_reg_701 <= add_ln272_1_fu_1044_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                phi_ln272_reg_701 <= reg_r_q0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                phi_ln272_reg_701 <= add_ln272_fu_1036_p2;
            end if; 
        end if;
    end process;

    reg_861_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
                reg_861 <= reg_r_q0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                reg_861 <= reg_r_q1;
            end if; 
        end if;
    end process;

    reg_868_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
                reg_868 <= reg_r_q1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                reg_868 <= reg_r_q0;
            end if; 
        end if;
    end process;

    storemerge12_reg_580_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((trunc_ln_reg_1640 = ap_const_lv4_6)) then
                if (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state22))) then 
                    storemerge12_reg_580 <= ap_const_lv1_0;
                elsif (((icmp_ln170_reg_1809 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23))) then 
                    storemerge12_reg_580 <= icmp_ln174_reg_1813;
                end if;
            end if; 
        end if;
    end process;

    storemerge14_reg_569_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((trunc_ln_reg_1640 = ap_const_lv4_6)) then
                if (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state22))) then 
                    storemerge14_reg_569 <= ap_const_lv1_0;
                elsif (((icmp_ln170_reg_1809 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23))) then 
                    storemerge14_reg_569 <= xor_ln174_fu_1263_p2;
                end if;
            end if; 
        end if;
    end process;

    storemerge17_reg_602_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((trunc_ln_reg_1640 = ap_const_lv4_A)) then
                if (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state22))) then 
                    storemerge17_reg_602 <= ap_const_lv1_0;
                elsif (((icmp_ln148_reg_1819 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23))) then 
                    storemerge17_reg_602 <= icmp_ln152_reg_1823;
                end if;
            end if; 
        end if;
    end process;

    storemerge19_reg_591_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((trunc_ln_reg_1640 = ap_const_lv4_A)) then
                if (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state22))) then 
                    storemerge19_reg_591 <= ap_const_lv1_0;
                elsif (((icmp_ln148_reg_1819 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23))) then 
                    storemerge19_reg_591 <= xor_ln152_fu_1287_p2;
                end if;
            end if; 
        end if;
    end process;

    storemerge22_reg_624_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
                storemerge22_reg_624 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
                storemerge22_reg_624 <= icmp_ln131_reg_1841;
            end if; 
        end if;
    end process;

    storemerge24_reg_613_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
                storemerge24_reg_613 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
                storemerge24_reg_613 <= xor_ln131_fu_1385_p2;
            end if; 
        end if;
    end process;

    storemerge28_reg_646_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state28)) then
                if ((icmp_ln106_fu_1407_p2 = ap_const_lv1_1)) then 
                    storemerge28_reg_646 <= ap_const_lv1_0;
                elsif ((icmp_ln106_fu_1407_p2 = ap_const_lv1_0)) then 
                    storemerge28_reg_646 <= icmp_ln110_fu_1413_p2;
                end if;
            end if; 
        end if;
    end process;

    storemerge30_reg_635_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state28)) then
                if ((icmp_ln106_fu_1407_p2 = ap_const_lv1_1)) then 
                    storemerge30_reg_635 <= ap_const_lv1_0;
                elsif ((icmp_ln106_fu_1407_p2 = ap_const_lv1_0)) then 
                    storemerge30_reg_635 <= xor_ln110_fu_1425_p2;
                end if;
            end if; 
        end if;
    end process;

    storemerge34_reg_668_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_5))) then
                if ((icmp_ln85_fu_1509_p2 = ap_const_lv1_1)) then 
                    storemerge34_reg_668 <= ap_const_lv1_0;
                elsif ((icmp_ln85_fu_1509_p2 = ap_const_lv1_0)) then 
                    storemerge34_reg_668 <= icmp_ln89_fu_1514_p2;
                end if;
            end if; 
        end if;
    end process;

    storemerge36_reg_657_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_5))) then
                if ((icmp_ln85_fu_1509_p2 = ap_const_lv1_1)) then 
                    storemerge36_reg_657 <= ap_const_lv1_0;
                elsif ((icmp_ln85_fu_1509_p2 = ap_const_lv1_0)) then 
                    storemerge36_reg_657 <= xor_ln89_fu_1525_p2;
                end if;
            end if; 
        end if;
    end process;

    storemerge41_reg_690_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_1))) then
                if ((icmp_ln57_fu_1537_p2 = ap_const_lv1_1)) then 
                    storemerge41_reg_690 <= ap_const_lv1_0;
                elsif ((icmp_ln57_fu_1537_p2 = ap_const_lv1_0)) then 
                    storemerge41_reg_690 <= icmp_ln61_fu_1542_p2;
                end if;
            end if; 
        end if;
    end process;

    storemerge43_reg_679_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_1))) then
                if ((icmp_ln57_fu_1537_p2 = ap_const_lv1_1)) then 
                    storemerge43_reg_679 <= ap_const_lv1_0;
                elsif ((icmp_ln57_fu_1537_p2 = ap_const_lv1_0)) then 
                    storemerge43_reg_679 <= xor_ln61_fu_1553_p2;
                end if;
            end if; 
        end if;
    end process;

    storemerge7_reg_558_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                if ((icmp_ln191_fu_1151_p2 = ap_const_lv1_1)) then 
                    storemerge7_reg_558 <= ap_const_lv1_0;
                elsif ((icmp_ln191_fu_1151_p2 = ap_const_lv1_0)) then 
                    storemerge7_reg_558 <= icmp_ln195_fu_1157_p2;
                end if;
            end if; 
        end if;
    end process;

    storemerge9_reg_547_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                if ((icmp_ln191_fu_1151_p2 = ap_const_lv1_1)) then 
                    storemerge9_reg_547 <= ap_const_lv1_0;
                elsif ((icmp_ln191_fu_1151_p2 = ap_const_lv1_0)) then 
                    storemerge9_reg_547 <= xor_ln195_fu_1169_p2;
                end if;
            end if; 
        end if;
    end process;

    z_r_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln191_fu_1151_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                z_r <= ap_const_lv1_1_7;
            elsif (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_A))) then 
                z_r <= ap_const_lv1_1_6;
            elsif (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_6))) then 
                z_r <= ap_const_lv1_1_5;
            elsif (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
                z_r <= ap_const_lv1_1_4;
            elsif (((icmp_ln106_fu_1407_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state28))) then 
                z_r <= ap_const_lv1_1_3;
            elsif (((icmp_ln57_fu_1537_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_1))) then 
                z_r <= ap_const_lv1_1_2;
            elsif (((icmp_ln85_fu_1509_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_5))) then 
                z_r <= ap_const_lv1_1_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state26) or ((icmp_ln57_fu_1537_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_1)) or ((icmp_ln85_fu_1509_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_5)) or ((icmp_ln106_fu_1407_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state28)) or ((icmp_ln148_reg_1819 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_A)) or ((icmp_ln170_reg_1809 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_6)) or ((icmp_ln191_fu_1151_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18)))) then 
                z_r <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                IR_read_reg_1602 <= IR;
                PC_read_reg_1589 <= PC;
                pc_offset6_reg_1618 <= pc_offset6_fu_889_p1;
                pc_offset9_reg_1624 <= pc_offset9_fu_897_p1;
                trunc_ln1_1_reg_1613 <= trunc_ln1_1_fu_885_p1;
                trunc_ln1_5_reg_1634 <= trunc_ln1_5_fu_901_p1;
                trunc_ln_reg_1640 <= IR(15 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state28)) then
                add_ln101_reg_1857 <= grp_fu_838_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then
                add_ln164_reg_1804 <= grp_fu_838_p2;
                icmp_ln148_reg_1819 <= grp_fu_843_p2;
                icmp_ln152_reg_1823 <= grp_fu_849_p2;
                icmp_ln170_reg_1809 <= grp_fu_843_p2;
                icmp_ln174_reg_1813 <= grp_fu_849_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                add_ln168_reg_1784 <= add_ln168_fu_1196_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                add_ln186_reg_1765 <= grp_fu_838_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                add_ln207_reg_1754 <= grp_fu_838_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                add_ln214_reg_1738 <= grp_fu_838_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                add_ln225_reg_1728 <= add_ln225_fu_1066_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state30)) then
                add_ln52_reg_1881 <= add_ln52_fu_1502_p2;
                and_ln80_reg_1875 <= and_ln80_fu_1472_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state25)) then
                icmp_ln131_reg_1841 <= grp_fu_849_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then
                or_ln1_1_reg_1829 <= or_ln1_1_fu_1338_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_A)))) then
                reg_855 <= grp_fu_807_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln_reg_1640 = ap_const_lv4_A)) or ((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln_reg_1640 = ap_const_lv4_6)))) then
                reg_875 <= IR_read_reg_1602(11 downto 9);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_5)))) then
                reg_879 <= grp_fu_838_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state36)) then
                reg_load_14_reg_1913 <= reg_r_q0;
                reg_load_15_reg_1918 <= reg_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state37)) then
                reg_load_16_reg_1923 <= reg_r_q0;
                reg_load_17_reg_1928 <= reg_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_3_reg_1677 <= IR_read_reg_1602(11 downto 11);
                tmp_4_reg_1683 <= IR_read_reg_1602(10 downto 10);
                tmp_5_reg_1689 <= IR_read_reg_1602(9 downto 9);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                trunc_ln17_reg_1700 <= IR_read_reg_1602(8 downto 6);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, trunc_ln_fu_905_p4, trunc_ln_reg_1640, ap_CS_fsm_state31, grp_fu_813_p3, ap_CS_fsm_state4, grp_fu_843_p2, ap_CS_fsm_state25)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and ((trunc_ln_fu_905_p4 = ap_const_lv4_1) or (trunc_ln_fu_905_p4 = ap_const_lv4_5)))) then
                    ap_NS_fsm <= ap_ST_fsm_state30;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_9))) then
                    ap_NS_fsm <= ap_ST_fsm_state27;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_2))) then
                    ap_NS_fsm <= ap_ST_fsm_state24;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and ((trunc_ln_fu_905_p4 = ap_const_lv4_8) or ((trunc_ln_fu_905_p4 = ap_const_lv4_D) or (trunc_ln_fu_905_p4 = ap_const_lv4_F))))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and ((trunc_ln_fu_905_p4 = ap_const_lv4_6) or (trunc_ln_fu_905_p4 = ap_const_lv4_A)))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_E))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_3))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_B))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_7))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_C))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_4))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_fu_813_p3 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                if (((grp_fu_843_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_state26;
                end if;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state31) and (trunc_ln_reg_1640 = ap_const_lv4_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state33;
                else
                    ap_NS_fsm <= ap_ST_fsm_state32;
                end if;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    N <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln248_fu_975_p2),16));

    N_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            N_ap_vld <= ap_const_logic_1;
        else 
            N_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    P <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln249_fu_989_p2),16));

    PC_out_ap_vld_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            PC_out_ap_vld <= ap_const_logic_1;
        else 
            PC_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    P_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            P_ap_vld <= ap_const_logic_1;
        else 
            P_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    R0_ap_vld_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            R0_ap_vld <= ap_const_logic_1;
        else 
            R0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    R1_ap_vld_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            R1_ap_vld <= ap_const_logic_1;
        else 
            R1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    R2_ap_vld_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            R2_ap_vld <= ap_const_logic_1;
        else 
            R2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    R3_ap_vld_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            R3_ap_vld <= ap_const_logic_1;
        else 
            R3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    R4_ap_vld_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            R4_ap_vld <= ap_const_logic_1;
        else 
            R4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    R5_ap_vld_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            R5_ap_vld <= ap_const_logic_1;
        else 
            R5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    R6_ap_vld_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            R6_ap_vld <= ap_const_logic_1;
        else 
            R6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    R7_ap_vld_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            R7_ap_vld <= ap_const_logic_1;
        else 
            R7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    Z <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln250_fu_1003_p2),16));

    Z_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            Z_ap_vld <= ap_const_logic_1;
        else 
            Z_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln125_1_fu_1357_p2 <= std_logic_vector(unsigned(zext_ln125_1_fu_1353_p1) + unsigned(reg_855));
    add_ln125_fu_1347_p2 <= std_logic_vector(unsigned(zext_ln32_fu_1344_p1) + unsigned(ap_const_lv10_1));
    add_ln146_1_fu_1215_p2 <= std_logic_vector(unsigned(zext_ln146_1_fu_1211_p1) + unsigned(reg_855));
    add_ln146_fu_1205_p2 <= std_logic_vector(unsigned(zext_ln32_1_fu_1202_p1) + unsigned(ap_const_lv10_1));
    add_ln168_fu_1196_p2 <= std_logic_vector(unsigned(reg_r_q0) + unsigned(zext_ln34_fu_1193_p1));
    add_ln189_fu_1140_p2 <= std_logic_vector(unsigned(add_ln186_reg_1765) + unsigned(zext_ln189_1_fu_1137_p1));
    add_ln210_1_fu_1127_p2 <= std_logic_vector(unsigned(zext_ln210_1_fu_1123_p1) + unsigned(add_ln207_reg_1754));
    add_ln210_fu_1117_p2 <= std_logic_vector(unsigned(zext_ln32_2_fu_1114_p1) + unsigned(ap_const_lv10_1));
    add_ln217_1_fu_1094_p2 <= std_logic_vector(unsigned(zext_ln217_1_fu_1090_p1) + unsigned(add_ln214_reg_1738));
    add_ln217_fu_1084_p2 <= std_logic_vector(unsigned(zext_ln32_3_fu_1076_p1) + unsigned(ap_const_lv10_1));
    add_ln225_fu_1066_p2 <= std_logic_vector(unsigned(reg_r_q0) + unsigned(zext_ln34_1_fu_1058_p1));
    add_ln272_1_fu_1044_p2 <= std_logic_vector(unsigned(zext_ln237_fu_1041_p1) + unsigned(PC_read_reg_1589));
    add_ln272_fu_1036_p2 <= std_logic_vector(unsigned(zext_ln272_fu_1032_p1) + unsigned(PC_read_reg_1589));
    add_ln52_fu_1502_p2 <= std_logic_vector(unsigned(reg_r_q1) + unsigned(select_ln51_fu_1494_p3));
    and_ln248_fu_975_p2 <= (tmp_3_reg_1677 and n_r);
    and_ln249_fu_989_p2 <= (tmp_5_reg_1689 and p_r);
    and_ln250_fu_1003_p2 <= (z_r and tmp_4_reg_1683);
    and_ln80_fu_1472_p2 <= (select_ln79_fu_1464_p3 and reg_r_q1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state27 <= ap_CS_fsm(26);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state29 <= ap_CS_fsm(28);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state30 <= ap_CS_fsm(29);
    ap_CS_fsm_state31 <= ap_CS_fsm(30);
    ap_CS_fsm_state32 <= ap_CS_fsm(31);
    ap_CS_fsm_state33 <= ap_CS_fsm(32);
    ap_CS_fsm_state34 <= ap_CS_fsm(33);
    ap_CS_fsm_state35 <= ap_CS_fsm(34);
    ap_CS_fsm_state36 <= ap_CS_fsm(35);
    ap_CS_fsm_state37 <= ap_CS_fsm(36);
    ap_CS_fsm_state38 <= ap_CS_fsm(37);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;
    ap_ST_fsm_state35_blk <= ap_const_logic_0;
    ap_ST_fsm_state36_blk <= ap_const_logic_0;
    ap_ST_fsm_state37_blk <= ap_const_logic_0;
    ap_ST_fsm_state38_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_phi_mux_storemerge12_phi_fu_584_p4_assign_proc : process(trunc_ln_reg_1640, icmp_ln170_reg_1809, icmp_ln174_reg_1813, ap_CS_fsm_state23, storemerge12_reg_580)
    begin
        if (((icmp_ln170_reg_1809 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_6))) then 
            ap_phi_mux_storemerge12_phi_fu_584_p4 <= icmp_ln174_reg_1813;
        else 
            ap_phi_mux_storemerge12_phi_fu_584_p4 <= storemerge12_reg_580;
        end if; 
    end process;


    ap_phi_mux_storemerge14_phi_fu_573_p4_assign_proc : process(trunc_ln_reg_1640, icmp_ln170_reg_1809, ap_CS_fsm_state23, xor_ln174_fu_1263_p2, storemerge14_reg_569)
    begin
        if (((icmp_ln170_reg_1809 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_6))) then 
            ap_phi_mux_storemerge14_phi_fu_573_p4 <= xor_ln174_fu_1263_p2;
        else 
            ap_phi_mux_storemerge14_phi_fu_573_p4 <= storemerge14_reg_569;
        end if; 
    end process;


    ap_phi_mux_storemerge17_phi_fu_606_p4_assign_proc : process(trunc_ln_reg_1640, icmp_ln148_reg_1819, icmp_ln152_reg_1823, ap_CS_fsm_state23, storemerge17_reg_602)
    begin
        if (((icmp_ln148_reg_1819 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_A))) then 
            ap_phi_mux_storemerge17_phi_fu_606_p4 <= icmp_ln152_reg_1823;
        else 
            ap_phi_mux_storemerge17_phi_fu_606_p4 <= storemerge17_reg_602;
        end if; 
    end process;


    ap_phi_mux_storemerge19_phi_fu_595_p4_assign_proc : process(trunc_ln_reg_1640, icmp_ln148_reg_1819, ap_CS_fsm_state23, xor_ln152_fu_1287_p2, storemerge19_reg_591)
    begin
        if (((icmp_ln148_reg_1819 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state23) and (trunc_ln_reg_1640 = ap_const_lv4_A))) then 
            ap_phi_mux_storemerge19_phi_fu_595_p4 <= xor_ln152_fu_1287_p2;
        else 
            ap_phi_mux_storemerge19_phi_fu_595_p4 <= storemerge19_reg_591;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_788_p4_assign_proc : process(or_ln1_1_reg_1829, phi_ln272_reg_701, PC_assign_10_reg_749, ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then
            if ((or_ln1_1_reg_1829 = ap_const_lv1_0)) then 
                ap_phi_mux_storemerge_phi_fu_788_p4 <= PC_assign_10_reg_749;
            elsif ((or_ln1_1_reg_1829 = ap_const_lv1_1)) then 
                ap_phi_mux_storemerge_phi_fu_788_p4 <= phi_ln272_reg_701;
            else 
                ap_phi_mux_storemerge_phi_fu_788_p4 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_storemerge_phi_fu_788_p4 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_fu_797_p4 <= IR(8 downto 6);
    grp_fu_807_p2 <= std_logic_vector(unsigned(PC) + unsigned(ap_const_lv16_1));
    grp_fu_813_p3 <= IR_read_reg_1602(11 downto 11);
    grp_fu_820_p4 <= IR_read_reg_1602(8 downto 6);
    grp_fu_829_p4 <= IR_read_reg_1602(11 downto 9);
    grp_fu_838_p2 <= std_logic_vector(unsigned(PC_read_reg_1589) + unsigned(ap_const_lv16_1));
    grp_fu_843_p2 <= "1" when (memory_q0 = ap_const_lv16_0) else "0";
    grp_fu_849_p2 <= "1" when (signed(memory_q0) > signed(ap_const_lv16_0)) else "0";
    icmp_ln106_fu_1407_p2 <= "1" when (reg_r_q0 = ap_const_lv16_FFFF) else "0";
    icmp_ln110_fu_1413_p2 <= "1" when (signed(reg_r_q0) < signed(ap_const_lv16_FFFF)) else "0";
    icmp_ln191_fu_1151_p2 <= "1" when (add_ln189_fu_1140_p2 = ap_const_lv16_0) else "0";
    icmp_ln195_fu_1157_p2 <= "1" when (signed(add_ln189_fu_1140_p2) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1_1_fu_1322_p2 <= "1" when (trunc_ln_reg_1640 = ap_const_lv4_4) else "0";
    icmp_ln1_2_fu_1333_p2 <= "1" when (trunc_ln_reg_1640 = ap_const_lv4_0) else "0";
    icmp_ln1_fu_1317_p2 <= "1" when (trunc_ln_reg_1640 = ap_const_lv4_C) else "0";
    icmp_ln57_fu_1537_p2 <= "1" when (add_ln52_reg_1881 = ap_const_lv16_0) else "0";
    icmp_ln61_fu_1542_p2 <= "1" when (signed(add_ln52_reg_1881) > signed(ap_const_lv16_0)) else "0";
    icmp_ln85_fu_1509_p2 <= "1" when (and_ln80_reg_1875 = ap_const_lv16_0) else "0";
    icmp_ln89_fu_1514_p2 <= "1" when (signed(and_ln80_reg_1875) > signed(ap_const_lv16_0)) else "0";

    memory_address0_assign_proc : process(ap_CS_fsm_state21, trunc_ln_reg_1640, ap_CS_fsm_state13, ap_CS_fsm_state20, ap_CS_fsm_state24, ap_CS_fsm_state14, ap_CS_fsm_state16, zext_ln225_2_fu_1072_p1, ap_CS_fsm_state10, zext_ln217_2_fu_1099_p1, sext_ln217_fu_1104_p1, zext_ln210_2_fu_1132_p1, zext_ln146_2_fu_1221_p1, zext_ln168_2_fu_1226_p1, sext_ln146_fu_1230_p1, zext_ln125_2_fu_1363_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            memory_address0 <= zext_ln125_2_fu_1363_p1(16 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln_reg_1640 = ap_const_lv4_A))) then 
            memory_address0 <= sext_ln146_fu_1230_p1(16 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln_reg_1640 = ap_const_lv4_6))) then 
            memory_address0 <= zext_ln168_2_fu_1226_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            memory_address0 <= zext_ln146_2_fu_1221_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            memory_address0 <= zext_ln210_2_fu_1132_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            memory_address0 <= sext_ln217_fu_1104_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            memory_address0 <= zext_ln217_2_fu_1099_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            memory_address0 <= zext_ln225_2_fu_1072_p1(16 - 1 downto 0);
        else 
            memory_address0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    memory_ce0_assign_proc : process(ap_CS_fsm_state21, trunc_ln_reg_1640, ap_CS_fsm_state13, ap_CS_fsm_state20, ap_CS_fsm_state24, ap_CS_fsm_state14, ap_CS_fsm_state16, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state13) or ((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln_reg_1640 = ap_const_lv4_A)) or ((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln_reg_1640 = ap_const_lv4_6)))) then 
            memory_ce0 <= ap_const_logic_1;
        else 
            memory_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    memory_d0_assign_proc : process(reg_r_q0, reg_r_q1, ap_CS_fsm_state14, ap_CS_fsm_state16, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            memory_d0 <= reg_r_q0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            memory_d0 <= reg_r_q1;
        else 
            memory_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    memory_we0_assign_proc : process(ap_CS_fsm_state14, ap_CS_fsm_state16, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            memory_we0 <= ap_const_logic_1;
        else 
            memory_we0 <= ap_const_logic_0;
        end if; 
    end process;

    n1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_reg_1677),16));

    n1_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            n1_ap_vld <= ap_const_logic_1;
        else 
            n1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or_ln1_1_fu_1338_p2 <= (or_ln1_fu_1327_p2 or icmp_ln1_2_fu_1333_p2);
    or_ln1_fu_1327_p2 <= (icmp_ln1_fu_1317_p2 or icmp_ln1_1_fu_1322_p2);
    or_ln251_1_fu_1019_p2 <= (or_ln251_fu_1013_p2 or and_ln248_fu_975_p2);
    or_ln251_fu_1013_p2 <= (and_ln250_fu_1003_p2 or and_ln249_fu_989_p2);
    p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_reg_1689),16));

    p1_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            p1_ap_vld <= ap_const_logic_1;
        else 
            p1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pc_offset6_fu_889_p1 <= IR(6 - 1 downto 0);
    pc_offset9_fu_897_p1 <= IR(9 - 1 downto 0);

    reg_r_address0_assign_proc : process(ap_CS_fsm_state1, trunc_ln_fu_905_p4, ap_CS_fsm_state35, trunc_ln_reg_1640, ap_CS_fsm_state7, ap_CS_fsm_state13, ap_CS_fsm_state18, ap_CS_fsm_state25, ap_CS_fsm_state27, ap_CS_fsm_state30, ap_CS_fsm_state36, ap_CS_fsm_state37, zext_ln225_1_fu_915_p1, zext_ln168_fu_920_p1, zext_ln83_fu_930_p1, zext_ln55_fu_940_p1, zext_ln230_fu_1053_p1, zext_ln217_fu_1079_p1, zext_ln189_fu_1146_p1, zext_ln125_fu_1368_p1, zext_ln104_fu_1390_p1, zext_ln80_1_fu_1459_p1, zext_ln52_1_fu_1489_p1, ap_CS_fsm_state34)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state37)) then 
            reg_r_address0 <= ap_const_lv3_6;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state36)) then 
            reg_r_address0 <= ap_const_lv3_4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            reg_r_address0 <= ap_const_lv3_2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state34)) then 
            reg_r_address0 <= ap_const_lv3_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state30) and (trunc_ln_reg_1640 = ap_const_lv4_1))) then 
            reg_r_address0 <= zext_ln52_1_fu_1489_p1(3 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state30) and (trunc_ln_reg_1640 = ap_const_lv4_5))) then 
            reg_r_address0 <= zext_ln80_1_fu_1459_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state27)) then 
            reg_r_address0 <= zext_ln104_fu_1390_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            reg_r_address0 <= zext_ln125_fu_1368_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            reg_r_address0 <= zext_ln189_fu_1146_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            reg_r_address0 <= zext_ln217_fu_1079_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            reg_r_address0 <= zext_ln230_fu_1053_p1(3 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_1))) then 
            reg_r_address0 <= zext_ln55_fu_940_p1(3 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_5))) then 
            reg_r_address0 <= zext_ln83_fu_930_p1(3 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_6))) then 
            reg_r_address0 <= zext_ln168_fu_920_p1(3 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_7))) then 
            reg_r_address0 <= zext_ln225_1_fu_915_p1(3 - 1 downto 0);
        else 
            reg_r_address0 <= "XXX";
        end if; 
    end process;


    reg_r_address1_assign_proc : process(ap_CS_fsm_state1, trunc_ln_fu_905_p4, ap_CS_fsm_state35, trunc_ln_reg_1640, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state9, ap_CS_fsm_state15, ap_CS_fsm_state22, ap_CS_fsm_state28, ap_CS_fsm_state36, ap_CS_fsm_state37, zext_ln80_fu_925_p1, zext_ln52_fu_935_p1, zext_ln240_fu_1049_p1, zext_ln225_fu_1061_p1, zext_ln210_fu_1109_p1, zext_ln168_1_fu_1235_p1, zext_ln146_fu_1246_p1, zext_ln104_1_fu_1402_p1, ap_CS_fsm_state34)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state36)) then 
            reg_r_address1 <= ap_const_lv3_5;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            reg_r_address1 <= ap_const_lv3_3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state34)) then 
            reg_r_address1 <= ap_const_lv3_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state28)) then 
            reg_r_address1 <= zext_ln104_1_fu_1402_p1(3 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_A))) then 
            reg_r_address1 <= zext_ln146_fu_1246_p1(3 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_6))) then 
            reg_r_address1 <= zext_ln168_1_fu_1235_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            reg_r_address1 <= zext_ln210_fu_1109_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            reg_r_address1 <= zext_ln225_fu_1061_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            reg_r_address1 <= zext_ln240_fu_1049_p1(3 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state37) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            reg_r_address1 <= ap_const_lv3_7;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_1))) then 
            reg_r_address1 <= zext_ln52_fu_935_p1(3 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_5))) then 
            reg_r_address1 <= zext_ln80_fu_925_p1(3 - 1 downto 0);
        else 
            reg_r_address1 <= "XXX";
        end if; 
    end process;


    reg_r_ce0_assign_proc : process(ap_CS_fsm_state1, trunc_ln_fu_905_p4, ap_CS_fsm_state35, trunc_ln_reg_1640, ap_CS_fsm_state7, ap_CS_fsm_state13, ap_CS_fsm_state18, ap_CS_fsm_state25, ap_CS_fsm_state27, ap_CS_fsm_state30, ap_CS_fsm_state36, ap_CS_fsm_state37, ap_CS_fsm_state34)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state34) or (ap_const_logic_1 = ap_CS_fsm_state37) or (ap_const_logic_1 = ap_CS_fsm_state36) or (ap_const_logic_1 = ap_CS_fsm_state27) or (ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state35) or ((ap_const_logic_1 = ap_CS_fsm_state30) and (trunc_ln_reg_1640 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state30) and (trunc_ln_reg_1640 = ap_const_lv4_5)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_5)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_6)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_7)))) then 
            reg_r_ce0 <= ap_const_logic_1;
        else 
            reg_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_r_ce1_assign_proc : process(ap_CS_fsm_state1, trunc_ln_fu_905_p4, ap_CS_fsm_state35, trunc_ln_reg_1640, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state9, ap_CS_fsm_state15, ap_CS_fsm_state22, ap_CS_fsm_state28, ap_CS_fsm_state36, ap_CS_fsm_state37, ap_CS_fsm_state34)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state34) or (ap_const_logic_1 = ap_CS_fsm_state37) or (ap_const_logic_1 = ap_CS_fsm_state36) or (ap_const_logic_1 = ap_CS_fsm_state28) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state35) or ((ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_A)) or ((ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_6)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln_fu_905_p4 = ap_const_lv4_5)))) then 
            reg_r_ce1 <= ap_const_logic_1;
        else 
            reg_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    reg_r_d0_assign_proc : process(memory_q0, trunc_ln_reg_1640, ap_CS_fsm_state18, ap_CS_fsm_state25, and_ln80_fu_1472_p2, ap_CS_fsm_state30, add_ln52_fu_1502_p2, add_ln189_fu_1140_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state30) and (trunc_ln_reg_1640 = ap_const_lv4_1))) then 
            reg_r_d0 <= add_ln52_fu_1502_p2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state30) and (trunc_ln_reg_1640 = ap_const_lv4_5))) then 
            reg_r_d0 <= and_ln80_fu_1472_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            reg_r_d0 <= memory_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            reg_r_d0 <= add_ln189_fu_1140_p2;
        else 
            reg_r_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    reg_r_d1_assign_proc : process(memory_q0, trunc_ln_reg_1640, PC_read_reg_1589, ap_CS_fsm_state4, ap_CS_fsm_state22, ap_CS_fsm_state28, xor_ln104_fu_1395_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state28)) then 
            reg_r_d1 <= xor_ln104_fu_1395_p2;
        elsif ((((ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_A)) or ((ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_6)))) then 
            reg_r_d1 <= memory_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_r_d1 <= PC_read_reg_1589;
        else 
            reg_r_d1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    reg_r_we0_assign_proc : process(trunc_ln_reg_1640, ap_CS_fsm_state18, ap_CS_fsm_state25, ap_CS_fsm_state30)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state18) or ((ap_const_logic_1 = ap_CS_fsm_state30) and (trunc_ln_reg_1640 = ap_const_lv4_1)) or ((ap_const_logic_1 = ap_CS_fsm_state30) and (trunc_ln_reg_1640 = ap_const_lv4_5)))) then 
            reg_r_we0 <= ap_const_logic_1;
        else 
            reg_r_we0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_r_we1_assign_proc : process(trunc_ln_reg_1640, ap_CS_fsm_state4, ap_CS_fsm_state22, ap_CS_fsm_state28)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state28) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_A)) or ((ap_const_logic_1 = ap_CS_fsm_state22) and (trunc_ln_reg_1640 = ap_const_lv4_6)))) then 
            reg_r_we1 <= ap_const_logic_1;
        else 
            reg_r_we1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln272_fu_1025_p3 <= 
        pc_offset9_reg_1624 when (or_ln251_1_fu_1019_p2(0) = '1') else 
        ap_const_lv9_1;
    select_ln51_fu_1494_p3 <= 
        zext_ln47_fu_1479_p1 when (tmp_fu_1482_p3(0) = '1') else 
        reg_r_q0;
    select_ln79_fu_1464_p3 <= 
        zext_ln75_fu_1449_p1 when (tmp_1_fu_1452_p3(0) = '1') else 
        reg_r_q0;
        sext_ln146_fu_1230_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(memory_q0),64));

    sext_ln217_fu_1104_p0 <= memory_q0;
        sext_ln217_fu_1104_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln217_fu_1104_p0),64));

    tmp_1_fu_1452_p3 <= IR_read_reg_1602(5 downto 5);
    tmp_fu_1482_p3 <= IR_read_reg_1602(5 downto 5);
    trunc_ln1_1_fu_885_p1 <= IR(11 - 1 downto 0);
    trunc_ln1_3_fu_893_p1 <= IR(3 - 1 downto 0);
    trunc_ln1_5_fu_901_p1 <= IR(5 - 1 downto 0);
    trunc_ln_fu_905_p4 <= IR(15 downto 12);
    xor_ln104_fu_1395_p2 <= (reg_r_q0 xor ap_const_lv16_FFFF);
    xor_ln110_fu_1425_p2 <= (icmp_ln110_fu_1413_p2 xor ap_const_lv1_1);
    xor_ln131_fu_1385_p2 <= (icmp_ln131_reg_1841 xor ap_const_lv1_1);
    xor_ln152_fu_1287_p2 <= (icmp_ln152_reg_1823 xor ap_const_lv1_1);
    xor_ln174_fu_1263_p2 <= (icmp_ln174_reg_1813 xor ap_const_lv1_1);
    xor_ln195_fu_1169_p2 <= (icmp_ln195_fu_1157_p2 xor ap_const_lv1_1);
    xor_ln61_fu_1553_p2 <= (icmp_ln61_fu_1542_p2 xor ap_const_lv1_1);
    xor_ln89_fu_1525_p2 <= (icmp_ln89_fu_1514_p2 xor ap_const_lv1_1);
    z1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_1683),16));

    z1_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            z1_ap_vld <= ap_const_logic_1;
        else 
            z1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln104_1_fu_1402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_829_p4),64));
    zext_ln104_fu_1390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_820_p4),64));
    zext_ln125_1_fu_1353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln125_fu_1347_p2),16));
    zext_ln125_2_fu_1363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln125_1_fu_1357_p2),64));
    zext_ln125_fu_1368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_829_p4),64));
    zext_ln146_1_fu_1211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln146_fu_1205_p2),16));
    zext_ln146_2_fu_1221_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln146_1_fu_1215_p2),64));
    zext_ln146_fu_1246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_875),64));
    zext_ln168_1_fu_1235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_875),64));
    zext_ln168_2_fu_1226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln168_reg_1784),64));
    zext_ln168_fu_920_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_797_p4),64));
    zext_ln189_1_fu_1137_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pc_offset9_reg_1624),16));
    zext_ln189_fu_1146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_829_p4),64));
    zext_ln210_1_fu_1123_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln210_fu_1117_p2),16));
    zext_ln210_2_fu_1132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln210_1_fu_1127_p2),64));
    zext_ln210_fu_1109_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_829_p4),64));
    zext_ln217_1_fu_1090_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln217_fu_1084_p2),16));
    zext_ln217_2_fu_1099_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln217_1_fu_1094_p2),64));
    zext_ln217_fu_1079_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_829_p4),64));
    zext_ln225_1_fu_915_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_797_p4),64));
    zext_ln225_2_fu_1072_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln225_reg_1728),64));
    zext_ln225_fu_1061_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_829_p4),64));
    zext_ln230_fu_1053_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_820_p4),64));
    zext_ln237_fu_1041_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1_1_reg_1613),16));
    zext_ln240_fu_1049_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln17_reg_1700),64));
    zext_ln272_fu_1032_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln272_fu_1025_p3),16));
    zext_ln32_1_fu_1202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pc_offset9_reg_1624),10));
    zext_ln32_2_fu_1114_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pc_offset9_reg_1624),10));
    zext_ln32_3_fu_1076_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pc_offset9_reg_1624),10));
    zext_ln32_fu_1344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pc_offset9_reg_1624),10));
    zext_ln34_1_fu_1058_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pc_offset6_reg_1618),16));
    zext_ln34_fu_1193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pc_offset6_reg_1618),16));
    zext_ln47_fu_1479_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1_5_reg_1634),16));
    zext_ln52_1_fu_1489_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_829_p4),64));
    zext_ln52_fu_935_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_797_p4),64));
    zext_ln55_fu_940_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1_3_fu_893_p1),64));
    zext_ln75_fu_1449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1_5_reg_1634),16));
    zext_ln80_1_fu_1459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_829_p4),64));
    zext_ln80_fu_925_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_797_p4),64));
    zext_ln83_fu_930_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1_3_fu_893_p1),64));
end behav;
