# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/aluhls/aluhls/aluhls.srcs/sources_1/bd/alu/ip/alu_auto_ds_1/alu_auto_ds_1.xci
# IP: The module: 'alu_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/aluhls/aluhls/aluhls.gen/sources_1/bd/alu/ip/alu_auto_ds_1/alu_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_auto_ds_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/aluhls/aluhls/aluhls.gen/sources_1/bd/alu/ip/alu_auto_ds_1/alu_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/aluhls/aluhls/aluhls.srcs/sources_1/bd/alu/ip/alu_auto_ds_1/alu_auto_ds_1.xci
# IP: The module: 'alu_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/aluhls/aluhls/aluhls.gen/sources_1/bd/alu/ip/alu_auto_ds_1/alu_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/aluhls/aluhls/aluhls.gen/sources_1/bd/alu/ip/alu_auto_ds_1/alu_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
