# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gpio_led/gpio_led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_led || ORIG_REF_NAME==gpio_led} -quiet] -quiet

# IP: bd/gpio_led/ip/gpio_led_processing_system7_0_0/gpio_led_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_led_processing_system7_0_0 || ORIG_REF_NAME==gpio_led_processing_system7_0_0} -quiet] -quiet

# IP: bd/gpio_led/ip/gpio_led_axi_gpio_0_0/gpio_led_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_led_axi_gpio_0_0 || ORIG_REF_NAME==gpio_led_axi_gpio_0_0} -quiet] -quiet

# IP: bd/gpio_led/ip/gpio_led_axi_gpio_0_1/gpio_led_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_led_axi_gpio_0_1 || ORIG_REF_NAME==gpio_led_axi_gpio_0_1} -quiet] -quiet

# IP: bd/gpio_led/ip/gpio_led_axi_gpio_0_2/gpio_led_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_led_axi_gpio_0_2 || ORIG_REF_NAME==gpio_led_axi_gpio_0_2} -quiet] -quiet

# IP: bd/gpio_led/ip/gpio_led_xbar_0/gpio_led_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_led_xbar_0 || ORIG_REF_NAME==gpio_led_xbar_0} -quiet] -quiet

# IP: bd/gpio_led/ip/gpio_led_auto_pc_0/gpio_led_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_led_auto_pc_0 || ORIG_REF_NAME==gpio_led_auto_pc_0} -quiet] -quiet

# IP: bd/gpio_led/ip/gpio_led_ps7_0_axi_periph_0/gpio_led_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_led_ps7_0_axi_periph_0 || ORIG_REF_NAME==gpio_led_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/gpio_led/ip/gpio_led_rst_ps7_0_100M_0/gpio_led_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_led_rst_ps7_0_100M_0 || ORIG_REF_NAME==gpio_led_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/per/GPIO_LED/GPIO_LED.gen/sources_1/bd/gpio_led/gpio_led_ooc.xdc
