-- ==============================================================
-- Generated by Vitis HLS v2023.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ALU is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC );
end;


architecture behav of ALU is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ALU_ALU,hls_ip_2023_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.420000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=182,HLS_SYN_LUT=1108,HLS_VERSION=2023_2_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

    signal a : STD_LOGIC_VECTOR (31 downto 0);
    signal b : STD_LOGIC_VECTOR (31 downto 0);
    signal op : STD_LOGIC_VECTOR (31 downto 0);
    signal result : STD_LOGIC_VECTOR (31 downto 0);
    signal result_ap_vld : STD_LOGIC;
    signal ap_rst_n_inv : STD_LOGIC;
    signal op_read_read_fu_66_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln41_fu_98_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln40_fu_113_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln39_fu_128_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ashr_ln38_fu_137_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln37_fu_144_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln36_fu_151_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln35_fu_158_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln34_fu_165_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln33_fu_178_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln32_fu_191_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln31_fu_198_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln30_fu_205_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln29_fu_212_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln41_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_fu_107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln33_fu_172_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln32_fu_185_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ALU_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        a : OUT STD_LOGIC_VECTOR (31 downto 0);
        b : OUT STD_LOGIC_VECTOR (31 downto 0);
        op : OUT STD_LOGIC_VECTOR (31 downto 0);
        result : IN STD_LOGIC_VECTOR (31 downto 0);
        result_ap_vld : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component ALU_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        a => a,
        b => b,
        op => op,
        result => result,
        result_ap_vld => result_ap_vld);




    add_ln29_fu_212_p2 <= std_logic_vector(unsigned(b) + unsigned(a));
    and_ln32_fu_185_p2 <= (b and a);
    and_ln34_fu_165_p2 <= (b and a);

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ashr_ln38_fu_137_p2 <= std_logic_vector(shift_right(signed(a),to_integer(unsigned('0' & b(31-1 downto 0)))));
    icmp_ln39_fu_122_p2 <= "1" when (signed(a) > signed(b)) else "0";
    icmp_ln40_fu_107_p2 <= "1" when (signed(a) < signed(b)) else "0";
    icmp_ln41_fu_92_p2 <= "1" when (a = b) else "0";
    op_read_read_fu_66_p2 <= op;
    or_ln33_fu_172_p2 <= (b or a);
    or_ln35_fu_158_p2 <= (b or a);

    result_assign_proc : process(op_read_read_fu_66_p2, select_ln41_fu_98_p3, select_ln40_fu_113_p3, select_ln39_fu_128_p3, ashr_ln38_fu_137_p2, shl_ln37_fu_144_p2, xor_ln36_fu_151_p2, or_ln35_fu_158_p2, and_ln34_fu_165_p2, xor_ln33_fu_178_p2, xor_ln32_fu_191_p2, xor_ln31_fu_198_p2, sub_ln30_fu_205_p2, add_ln29_fu_212_p2)
    begin
        if ((not((op_read_read_fu_66_p2 = ap_const_lv32_0)) and not((op_read_read_fu_66_p2 = ap_const_lv32_1)) and not((op_read_read_fu_66_p2 = ap_const_lv32_2)) and not((op_read_read_fu_66_p2 = ap_const_lv32_3)) and not((op_read_read_fu_66_p2 = ap_const_lv32_4)) and not((op_read_read_fu_66_p2 = ap_const_lv32_5)) and not((op_read_read_fu_66_p2 = ap_const_lv32_6)) and not((op_read_read_fu_66_p2 = ap_const_lv32_7)) and not((op_read_read_fu_66_p2 = ap_const_lv32_8)) and not((op_read_read_fu_66_p2 = ap_const_lv32_9)) and not((op_read_read_fu_66_p2 = ap_const_lv32_A)) and not((op_read_read_fu_66_p2 = ap_const_lv32_B)) and not((op_read_read_fu_66_p2 = ap_const_lv32_C)))) then 
            result <= ap_const_lv32_0;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_0)) then 
            result <= add_ln29_fu_212_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_1)) then 
            result <= sub_ln30_fu_205_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_2)) then 
            result <= xor_ln31_fu_198_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_3)) then 
            result <= xor_ln32_fu_191_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_4)) then 
            result <= xor_ln33_fu_178_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_5)) then 
            result <= and_ln34_fu_165_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_6)) then 
            result <= or_ln35_fu_158_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_7)) then 
            result <= xor_ln36_fu_151_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_8)) then 
            result <= shl_ln37_fu_144_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_9)) then 
            result <= ashr_ln38_fu_137_p2;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_A)) then 
            result <= select_ln39_fu_128_p3;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_B)) then 
            result <= select_ln40_fu_113_p3;
        elsif ((op_read_read_fu_66_p2 = ap_const_lv32_C)) then 
            result <= select_ln41_fu_98_p3;
        else 
            result <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    result_ap_vld_assign_proc : process(op_read_read_fu_66_p2)
    begin
        if (((op_read_read_fu_66_p2 = ap_const_lv32_0) or (op_read_read_fu_66_p2 = ap_const_lv32_1) or (op_read_read_fu_66_p2 = ap_const_lv32_2) or (op_read_read_fu_66_p2 = ap_const_lv32_3) or (op_read_read_fu_66_p2 = ap_const_lv32_4) or (op_read_read_fu_66_p2 = ap_const_lv32_5) or (op_read_read_fu_66_p2 = ap_const_lv32_6) or (op_read_read_fu_66_p2 = ap_const_lv32_7) or (op_read_read_fu_66_p2 = ap_const_lv32_8) or (op_read_read_fu_66_p2 = ap_const_lv32_9) or (op_read_read_fu_66_p2 = ap_const_lv32_A) or (op_read_read_fu_66_p2 = ap_const_lv32_B) or (op_read_read_fu_66_p2 = ap_const_lv32_C) or (not((op_read_read_fu_66_p2 = ap_const_lv32_0)) and not((op_read_read_fu_66_p2 = ap_const_lv32_1)) and not((op_read_read_fu_66_p2 = ap_const_lv32_2)) and not((op_read_read_fu_66_p2 = ap_const_lv32_3)) and not((op_read_read_fu_66_p2 = ap_const_lv32_4)) and not((op_read_read_fu_66_p2 = ap_const_lv32_5)) and not((op_read_read_fu_66_p2 = ap_const_lv32_6)) and not((op_read_read_fu_66_p2 = ap_const_lv32_7)) and not((op_read_read_fu_66_p2 = ap_const_lv32_8)) 
    and not((op_read_read_fu_66_p2 = ap_const_lv32_9)) and not((op_read_read_fu_66_p2 = ap_const_lv32_A)) and not((op_read_read_fu_66_p2 = ap_const_lv32_B)) and not((op_read_read_fu_66_p2 = ap_const_lv32_C))))) then 
            result_ap_vld <= ap_const_logic_1;
        else 
            result_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln39_fu_128_p3 <= 
        a when (icmp_ln39_fu_122_p2(0) = '1') else 
        b;
    select_ln40_fu_113_p3 <= 
        a when (icmp_ln40_fu_107_p2(0) = '1') else 
        b;
    select_ln41_fu_98_p3 <= 
        a when (icmp_ln41_fu_92_p2(0) = '1') else 
        ap_const_lv32_0;
    shl_ln37_fu_144_p2 <= std_logic_vector(shift_left(unsigned(a),to_integer(unsigned('0' & b(31-1 downto 0)))));
    sub_ln30_fu_205_p2 <= std_logic_vector(unsigned(a) - unsigned(b));
    xor_ln31_fu_198_p2 <= (ap_const_lv32_FFFFFFFF xor a);
    xor_ln32_fu_191_p2 <= (ap_const_lv32_FFFFFFFF xor and_ln32_fu_185_p2);
    xor_ln33_fu_178_p2 <= (or_ln33_fu_172_p2 xor ap_const_lv32_FFFFFFFF);
    xor_ln36_fu_151_p2 <= (b xor a);
end behav;
