// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ALU_ALU,hls_ip_2023_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu5eg-sfvc784-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.728000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=182,HLS_SYN_LUT=1108,HLS_VERSION=2023_2_2}" *)

module ALU (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;

wire   [31:0] a;
wire   [31:0] b;
wire   [31:0] op;
reg   [31:0] result;
reg    result_ap_vld;
 reg    ap_rst_n_inv;
wire   [31:0] op_read_read_fu_66_p2;
wire   [31:0] select_ln41_fu_98_p3;
wire   [31:0] select_ln40_fu_113_p3;
wire   [31:0] select_ln39_fu_128_p3;
wire   [31:0] ashr_ln38_fu_137_p2;
wire   [31:0] shl_ln37_fu_144_p2;
wire   [31:0] xor_ln36_fu_151_p2;
wire   [31:0] or_ln35_fu_158_p2;
wire   [31:0] and_ln34_fu_165_p2;
wire   [31:0] xor_ln33_fu_178_p2;
wire   [31:0] xor_ln32_fu_191_p2;
wire   [31:0] xor_ln31_fu_198_p2;
wire   [31:0] sub_ln30_fu_205_p2;
wire   [31:0] add_ln29_fu_212_p2;
wire   [0:0] icmp_ln41_fu_92_p2;
wire   [0:0] icmp_ln40_fu_107_p2;
wire   [0:0] icmp_ln39_fu_122_p2;
wire   [31:0] or_ln33_fu_172_p2;
wire   [31:0] and_ln32_fu_185_p2;
wire    ap_ce_reg;

ALU_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .a(a),
    .b(b),
    .op(op),
    .result(result),
    .result_ap_vld(result_ap_vld)
);

always @ (*) begin
    if ((~(op_read_read_fu_66_p2 == 32'd0) & ~(op_read_read_fu_66_p2 == 32'd1) & ~(op_read_read_fu_66_p2 == 32'd2) & ~(op_read_read_fu_66_p2 == 32'd3) & ~(op_read_read_fu_66_p2 == 32'd4) & ~(op_read_read_fu_66_p2 == 32'd5) & ~(op_read_read_fu_66_p2 == 32'd6) & ~(op_read_read_fu_66_p2 == 32'd7) & ~(op_read_read_fu_66_p2 == 32'd8) & ~(op_read_read_fu_66_p2 == 32'd9) & ~(op_read_read_fu_66_p2 == 32'd10) & ~(op_read_read_fu_66_p2 == 32'd11) & ~(op_read_read_fu_66_p2 == 32'd12))) begin
        result = 32'd0;
    end else if ((op_read_read_fu_66_p2 == 32'd0)) begin
        result = add_ln29_fu_212_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd1)) begin
        result = sub_ln30_fu_205_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd2)) begin
        result = xor_ln31_fu_198_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd3)) begin
        result = xor_ln32_fu_191_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd4)) begin
        result = xor_ln33_fu_178_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd5)) begin
        result = and_ln34_fu_165_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd6)) begin
        result = or_ln35_fu_158_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd7)) begin
        result = xor_ln36_fu_151_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd8)) begin
        result = shl_ln37_fu_144_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd9)) begin
        result = ashr_ln38_fu_137_p2;
    end else if ((op_read_read_fu_66_p2 == 32'd10)) begin
        result = select_ln39_fu_128_p3;
    end else if ((op_read_read_fu_66_p2 == 32'd11)) begin
        result = select_ln40_fu_113_p3;
    end else if ((op_read_read_fu_66_p2 == 32'd12)) begin
        result = select_ln41_fu_98_p3;
    end else begin
        result = 'bx;
    end
end

always @ (*) begin
    if (((op_read_read_fu_66_p2 == 32'd0) | (op_read_read_fu_66_p2 == 32'd1) | (op_read_read_fu_66_p2 == 32'd2) | (op_read_read_fu_66_p2 == 32'd3) | (op_read_read_fu_66_p2 == 32'd4) | (op_read_read_fu_66_p2 == 32'd5) | (op_read_read_fu_66_p2 == 32'd6) | (op_read_read_fu_66_p2 == 32'd7) | (op_read_read_fu_66_p2 == 32'd8) | (op_read_read_fu_66_p2 == 32'd9) | (op_read_read_fu_66_p2 == 32'd10) | (op_read_read_fu_66_p2 == 32'd11) | (op_read_read_fu_66_p2 == 32'd12) | (~(op_read_read_fu_66_p2 == 32'd0) & ~(op_read_read_fu_66_p2 == 32'd1) & ~(op_read_read_fu_66_p2 == 32'd2) & ~(op_read_read_fu_66_p2 == 32'd3) & ~(op_read_read_fu_66_p2 == 32'd4) & ~(op_read_read_fu_66_p2 == 32'd5) & ~(op_read_read_fu_66_p2 == 32'd6) & ~(op_read_read_fu_66_p2 == 32'd7) & ~(op_read_read_fu_66_p2 == 32'd8) & ~(op_read_read_fu_66_p2 == 32'd9) & ~(op_read_read_fu_66_p2 == 32'd10) & ~(op_read_read_fu_66_p2 == 32'd11) & ~(op_read_read_fu_66_p2 == 32'd12)))) begin
        result_ap_vld = 1'b1;
    end else begin
        result_ap_vld = 1'b0;
    end
end

assign add_ln29_fu_212_p2 = (b + a);

assign and_ln32_fu_185_p2 = (b & a);

assign and_ln34_fu_165_p2 = (b & a);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ashr_ln38_fu_137_p2 = $signed(a) >>> b;

assign icmp_ln39_fu_122_p2 = (($signed(a) > $signed(b)) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_107_p2 = (($signed(a) < $signed(b)) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_92_p2 = ((a == b) ? 1'b1 : 1'b0);

assign or_ln33_fu_172_p2 = (b | a);

assign or_ln35_fu_158_p2 = (b | a);

assign select_ln39_fu_128_p3 = ((icmp_ln39_fu_122_p2[0:0] == 1'b1) ? a : b);

assign select_ln40_fu_113_p3 = ((icmp_ln40_fu_107_p2[0:0] == 1'b1) ? a : b);

assign select_ln41_fu_98_p3 = ((icmp_ln41_fu_92_p2[0:0] == 1'b1) ? a : 32'd0);

assign shl_ln37_fu_144_p2 = a << b;

assign sub_ln30_fu_205_p2 = (a - b);

assign xor_ln31_fu_198_p2 = (32'd4294967295 ^ a);

assign xor_ln32_fu_191_p2 = (32'd4294967295 ^ and_ln32_fu_185_p2);

assign xor_ln33_fu_178_p2 = (or_ln33_fu_172_p2 ^ 32'd4294967295);

assign xor_ln36_fu_151_p2 = (b ^ a);

assign op_read_read_fu_66_p2 = op;

endmodule //ALU
