# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/alu/alu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu || ORIG_REF_NAME==alu} -quiet] -quiet

# IP: bd/alu/ip/alu_zynq_ultra_ps_e_0_0/alu_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==alu_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/alu/ip/alu_ALU_0_0/alu_ALU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_ALU_0_0 || ORIG_REF_NAME==alu_ALU_0_0} -quiet] -quiet

# IP: bd/alu/ip/alu_xbar_0/alu_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_xbar_0 || ORIG_REF_NAME==alu_xbar_0} -quiet] -quiet

# IP: bd/alu/ip/alu_auto_ds_0/alu_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_auto_ds_0 || ORIG_REF_NAME==alu_auto_ds_0} -quiet] -quiet

# IP: bd/alu/ip/alu_auto_pc_0/alu_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_auto_pc_0 || ORIG_REF_NAME==alu_auto_pc_0} -quiet] -quiet

# IP: bd/alu/ip/alu_auto_ds_1/alu_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_auto_ds_1 || ORIG_REF_NAME==alu_auto_ds_1} -quiet] -quiet

# IP: bd/alu/ip/alu_auto_pc_1/alu_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_auto_pc_1 || ORIG_REF_NAME==alu_auto_pc_1} -quiet] -quiet

# IP: bd/alu/ip/alu_ps8_0_axi_periph_0/alu_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_ps8_0_axi_periph_0 || ORIG_REF_NAME==alu_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/alu/ip/alu_rst_ps8_0_100M_0/alu_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_rst_ps8_0_100M_0 || ORIG_REF_NAME==alu_rst_ps8_0_100M_0} -quiet] -quiet

# XDC: c:/Users/phat6/OneDrive/Desktop/testnaykia/vivado/aluhls/aluhls/aluhls.gen/sources_1/bd/alu/alu_ooc.xdc
