# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/LVTN/lc3_24/lc3_24.srcs/sources_1/bd/design_1/ip/design_1_lc3_0_0/design_1_lc3_0_0.xci
# IP: The module: 'design_1_lc3_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LVTN/lc3_24/lc3_24.gen/sources_1/bd/design_1/ip/design_1_lc3_0_0/constraints/lc3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_lc3_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/LVTN/lc3_24/lc3_24.srcs/sources_1/bd/design_1/ip/design_1_lc3_0_0/design_1_lc3_0_0.xci
# IP: The module: 'design_1_lc3_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LVTN/lc3_24/lc3_24.gen/sources_1/bd/design_1/ip/design_1_lc3_0_0/constraints/lc3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_lc3_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
