// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lc3_lc3,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.154000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=64,HLS_SYN_DSP=0,HLS_SYN_FF=877,HLS_SYN_LUT=2034,HLS_VERSION=2023_2}" *)

module lc3 (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 38'd1;
parameter    ap_ST_fsm_state2 = 38'd2;
parameter    ap_ST_fsm_state3 = 38'd4;
parameter    ap_ST_fsm_state4 = 38'd8;
parameter    ap_ST_fsm_state5 = 38'd16;
parameter    ap_ST_fsm_state6 = 38'd32;
parameter    ap_ST_fsm_state7 = 38'd64;
parameter    ap_ST_fsm_state8 = 38'd128;
parameter    ap_ST_fsm_state9 = 38'd256;
parameter    ap_ST_fsm_state10 = 38'd512;
parameter    ap_ST_fsm_state11 = 38'd1024;
parameter    ap_ST_fsm_state12 = 38'd2048;
parameter    ap_ST_fsm_state13 = 38'd4096;
parameter    ap_ST_fsm_state14 = 38'd8192;
parameter    ap_ST_fsm_state15 = 38'd16384;
parameter    ap_ST_fsm_state16 = 38'd32768;
parameter    ap_ST_fsm_state17 = 38'd65536;
parameter    ap_ST_fsm_state18 = 38'd131072;
parameter    ap_ST_fsm_state19 = 38'd262144;
parameter    ap_ST_fsm_state20 = 38'd524288;
parameter    ap_ST_fsm_state21 = 38'd1048576;
parameter    ap_ST_fsm_state22 = 38'd2097152;
parameter    ap_ST_fsm_state23 = 38'd4194304;
parameter    ap_ST_fsm_state24 = 38'd8388608;
parameter    ap_ST_fsm_state25 = 38'd16777216;
parameter    ap_ST_fsm_state26 = 38'd33554432;
parameter    ap_ST_fsm_state27 = 38'd67108864;
parameter    ap_ST_fsm_state28 = 38'd134217728;
parameter    ap_ST_fsm_state29 = 38'd268435456;
parameter    ap_ST_fsm_state30 = 38'd536870912;
parameter    ap_ST_fsm_state31 = 38'd1073741824;
parameter    ap_ST_fsm_state32 = 38'd2147483648;
parameter    ap_ST_fsm_state33 = 38'd4294967296;
parameter    ap_ST_fsm_state34 = 38'd8589934592;
parameter    ap_ST_fsm_state35 = 38'd17179869184;
parameter    ap_ST_fsm_state36 = 38'd34359738368;
parameter    ap_ST_fsm_state37 = 38'd68719476736;
parameter    ap_ST_fsm_state38 = 38'd137438953472;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 9;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire   [15:0] IR;
wire   [15:0] PC;
reg    PC_out_ap_vld;
reg    R0_ap_vld;
reg    R1_ap_vld;
reg    R2_ap_vld;
reg    R3_ap_vld;
reg    R4_ap_vld;
reg    R5_ap_vld;
reg    R6_ap_vld;
reg    R7_ap_vld;
wire   [15:0] N;
reg    N_ap_vld;
wire   [15:0] Z;
reg    Z_ap_vld;
wire   [15:0] P;
reg    P_ap_vld;
wire   [15:0] n1;
reg    n1_ap_vld;
wire   [15:0] p1;
reg    p1_ap_vld;
wire   [15:0] z1;
reg    z1_ap_vld;
reg   [2:0] reg_r_address0;
reg    reg_r_ce0;
reg    reg_r_we0;
reg   [15:0] reg_r_d0;
wire   [15:0] reg_r_q0;
reg   [2:0] reg_r_address1;
reg    reg_r_ce1;
reg    reg_r_we1;
reg   [15:0] reg_r_d1;
wire   [15:0] reg_r_q1;
reg   [0:0] z_r;
reg   [0:0] n_r;
reg   [0:0] p_r;
reg   [15:0] memory_address0;
reg    memory_ce0;
reg    memory_we0;
reg   [15:0] memory_d0;
wire   [15:0] memory_q0;
wire   [15:0] grp_fu_807_p2;
reg   [15:0] reg_855;
(* fsm_encoding = "none" *) reg   [37:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] trunc_ln_fu_905_p4;
reg   [15:0] reg_861;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state35;
reg   [15:0] reg_868;
wire    ap_CS_fsm_state8;
wire   [2:0] grp_fu_829_p4;
reg   [2:0] reg_875;
wire    ap_CS_fsm_state21;
reg   [3:0] trunc_ln_reg_1640;
wire   [15:0] grp_fu_838_p2;
reg   [15:0] reg_879;
wire    ap_CS_fsm_state31;
reg   [15:0] PC_read_reg_1589;
reg   [15:0] IR_read_reg_1602;
wire   [10:0] trunc_ln1_1_fu_885_p1;
reg   [10:0] trunc_ln1_1_reg_1613;
wire   [5:0] pc_offset6_fu_889_p1;
reg   [5:0] pc_offset6_reg_1618;
wire   [8:0] pc_offset9_fu_897_p1;
reg   [8:0] pc_offset9_reg_1624;
wire   [4:0] trunc_ln1_5_fu_901_p1;
reg   [4:0] trunc_ln1_5_reg_1634;
wire   [0:0] grp_fu_813_p3;
reg   [0:0] tmp_3_reg_1677;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_4_reg_1683;
reg   [0:0] tmp_5_reg_1689;
wire   [15:0] add_ln272_fu_1036_p2;
wire    ap_CS_fsm_state3;
wire   [2:0] grp_fu_820_p4;
reg   [2:0] trunc_ln17_reg_1700;
wire    ap_CS_fsm_state4;
wire   [15:0] add_ln272_1_fu_1044_p2;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state9;
wire   [15:0] add_ln225_fu_1066_p2;
reg   [15:0] add_ln225_reg_1728;
wire    ap_CS_fsm_state11;
reg   [15:0] add_ln214_reg_1738;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg   [15:0] add_ln207_reg_1754;
wire    ap_CS_fsm_state15;
reg   [15:0] add_ln186_reg_1765;
wire    ap_CS_fsm_state17;
wire   [0:0] icmp_ln195_fu_1157_p2;
wire    ap_CS_fsm_state18;
wire   [0:0] xor_ln195_fu_1169_p2;
wire   [15:0] add_ln168_fu_1196_p2;
reg   [15:0] add_ln168_reg_1784;
wire    ap_CS_fsm_state20;
reg   [15:0] add_ln164_reg_1804;
wire    ap_CS_fsm_state22;
wire   [0:0] grp_fu_843_p2;
reg   [0:0] icmp_ln170_reg_1809;
wire   [0:0] grp_fu_849_p2;
reg   [0:0] icmp_ln174_reg_1813;
reg   [0:0] icmp_ln148_reg_1819;
reg   [0:0] icmp_ln152_reg_1823;
wire   [0:0] or_ln1_1_fu_1338_p2;
reg   [0:0] or_ln1_1_reg_1829;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
reg   [0:0] icmp_ln131_reg_1841;
wire    ap_CS_fsm_state25;
wire   [0:0] xor_ln131_fu_1385_p2;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
reg   [15:0] add_ln101_reg_1857;
wire    ap_CS_fsm_state28;
wire   [0:0] icmp_ln110_fu_1413_p2;
wire   [0:0] xor_ln110_fu_1425_p2;
wire   [15:0] and_ln80_fu_1472_p2;
reg   [15:0] and_ln80_reg_1875;
wire    ap_CS_fsm_state30;
wire   [15:0] add_ln52_fu_1502_p2;
reg   [15:0] add_ln52_reg_1881;
wire   [0:0] icmp_ln89_fu_1514_p2;
wire   [0:0] xor_ln89_fu_1525_p2;
wire   [0:0] icmp_ln61_fu_1542_p2;
wire   [0:0] xor_ln61_fu_1553_p2;
reg   [15:0] reg_load_14_reg_1913;
wire    ap_CS_fsm_state36;
reg   [15:0] reg_load_15_reg_1918;
reg   [15:0] reg_load_16_reg_1923;
wire    ap_CS_fsm_state37;
reg   [15:0] reg_load_17_reg_1928;
reg   [0:0] storemerge9_reg_547;
wire   [0:0] icmp_ln191_fu_1151_p2;
reg   [0:0] storemerge7_reg_558;
wire   [0:0] xor_ln174_fu_1263_p2;
reg   [0:0] ap_phi_mux_storemerge14_phi_fu_573_p4;
reg   [0:0] storemerge14_reg_569;
reg   [0:0] ap_phi_mux_storemerge12_phi_fu_584_p4;
reg   [0:0] storemerge12_reg_580;
wire   [0:0] xor_ln152_fu_1287_p2;
reg   [0:0] ap_phi_mux_storemerge19_phi_fu_595_p4;
reg   [0:0] storemerge19_reg_591;
reg   [0:0] ap_phi_mux_storemerge17_phi_fu_606_p4;
reg   [0:0] storemerge17_reg_602;
reg   [0:0] storemerge24_reg_613;
reg   [0:0] storemerge22_reg_624;
reg   [0:0] storemerge30_reg_635;
wire   [0:0] icmp_ln106_fu_1407_p2;
reg   [0:0] storemerge28_reg_646;
reg   [0:0] storemerge36_reg_657;
wire   [0:0] icmp_ln85_fu_1509_p2;
reg   [0:0] storemerge34_reg_668;
reg   [0:0] storemerge43_reg_679;
wire   [0:0] icmp_ln57_fu_1537_p2;
reg   [0:0] storemerge41_reg_690;
reg   [15:0] phi_ln272_reg_701;
reg   [15:0] PC_assign_10_reg_749;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
reg   [15:0] ap_phi_mux_storemerge_phi_fu_788_p4;
wire    ap_CS_fsm_state38;
wire   [63:0] zext_ln225_1_fu_915_p1;
wire   [63:0] zext_ln168_fu_920_p1;
wire   [63:0] zext_ln80_fu_925_p1;
wire   [63:0] zext_ln83_fu_930_p1;
wire   [63:0] zext_ln52_fu_935_p1;
wire   [63:0] zext_ln55_fu_940_p1;
wire   [63:0] zext_ln240_fu_1049_p1;
wire   [63:0] zext_ln230_fu_1053_p1;
wire   [63:0] zext_ln225_fu_1061_p1;
wire   [63:0] zext_ln225_2_fu_1072_p1;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln217_fu_1079_p1;
wire   [63:0] zext_ln217_2_fu_1099_p1;
wire  signed [63:0] sext_ln217_fu_1104_p1;
wire   [63:0] zext_ln210_fu_1109_p1;
wire   [63:0] zext_ln210_2_fu_1132_p1;
wire   [63:0] zext_ln189_fu_1146_p1;
wire   [63:0] zext_ln146_2_fu_1221_p1;
wire   [63:0] zext_ln168_2_fu_1226_p1;
wire  signed [63:0] sext_ln146_fu_1230_p1;
wire   [63:0] zext_ln168_1_fu_1235_p1;
wire   [63:0] zext_ln146_fu_1246_p1;
wire   [63:0] zext_ln125_2_fu_1363_p1;
wire   [63:0] zext_ln125_fu_1368_p1;
wire   [63:0] zext_ln104_fu_1390_p1;
wire   [63:0] zext_ln104_1_fu_1402_p1;
wire   [63:0] zext_ln80_1_fu_1459_p1;
wire   [63:0] zext_ln52_1_fu_1489_p1;
wire   [15:0] add_ln189_fu_1140_p2;
wire   [15:0] xor_ln104_fu_1395_p2;
wire    ap_CS_fsm_state34;
wire   [2:0] grp_fu_797_p4;
wire   [2:0] trunc_ln1_3_fu_893_p1;
wire   [0:0] and_ln248_fu_975_p2;
wire   [0:0] and_ln249_fu_989_p2;
wire   [0:0] and_ln250_fu_1003_p2;
wire   [0:0] or_ln251_fu_1013_p2;
wire   [0:0] or_ln251_1_fu_1019_p2;
wire   [8:0] select_ln272_fu_1025_p3;
wire   [15:0] zext_ln272_fu_1032_p1;
wire   [15:0] zext_ln237_fu_1041_p1;
wire   [15:0] zext_ln34_1_fu_1058_p1;
wire   [9:0] zext_ln32_3_fu_1076_p1;
wire   [9:0] add_ln217_fu_1084_p2;
wire   [15:0] zext_ln217_1_fu_1090_p1;
wire   [15:0] add_ln217_1_fu_1094_p2;
wire  signed [15:0] sext_ln217_fu_1104_p0;
wire   [9:0] zext_ln32_2_fu_1114_p1;
wire   [9:0] add_ln210_fu_1117_p2;
wire   [15:0] zext_ln210_1_fu_1123_p1;
wire   [15:0] add_ln210_1_fu_1127_p2;
wire   [15:0] zext_ln189_1_fu_1137_p1;
wire   [15:0] zext_ln34_fu_1193_p1;
wire   [9:0] zext_ln32_1_fu_1202_p1;
wire   [9:0] add_ln146_fu_1205_p2;
wire   [15:0] zext_ln146_1_fu_1211_p1;
wire   [15:0] add_ln146_1_fu_1215_p2;
wire   [0:0] icmp_ln1_1_fu_1322_p2;
wire   [0:0] icmp_ln1_fu_1317_p2;
wire   [0:0] icmp_ln1_2_fu_1333_p2;
wire   [0:0] or_ln1_fu_1327_p2;
wire   [9:0] zext_ln32_fu_1344_p1;
wire   [9:0] add_ln125_fu_1347_p2;
wire   [15:0] zext_ln125_1_fu_1353_p1;
wire   [15:0] add_ln125_1_fu_1357_p2;
wire   [0:0] tmp_1_fu_1452_p3;
wire   [15:0] zext_ln75_fu_1449_p1;
wire   [15:0] select_ln79_fu_1464_p3;
wire   [0:0] tmp_fu_1482_p3;
wire   [15:0] zext_ln47_fu_1479_p1;
wire   [15:0] select_ln51_fu_1494_p3;
reg   [37:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 z_r = 1'd0;
#0 n_r = 1'd0;
#0 p_r = 1'd0;
#0 ap_CS_fsm = 38'd1;
end

lc3_reg_r_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
reg_r_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(reg_r_address0),
    .ce0(reg_r_ce0),
    .we0(reg_r_we0),
    .d0(reg_r_d0),
    .q0(reg_r_q0),
    .address1(reg_r_address1),
    .ce1(reg_r_ce1),
    .we1(reg_r_we1),
    .d1(reg_r_d1),
    .q1(reg_r_q1)
);

lc3_memory_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 65536 ),
    .AddressWidth( 16 ))
memory_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(memory_address0),
    .ce0(memory_ce0),
    .we0(memory_we0),
    .d0(memory_d0),
    .q0(memory_q0)
);

lc3_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .IR(IR),
    .PC(PC),
    .PC_out(ap_phi_mux_storemerge_phi_fu_788_p4),
    .PC_out_ap_vld(PC_out_ap_vld),
    .R0(reg_861),
    .R0_ap_vld(R0_ap_vld),
    .R1(reg_868),
    .R1_ap_vld(R1_ap_vld),
    .R2(reg_load_14_reg_1913),
    .R2_ap_vld(R2_ap_vld),
    .R3(reg_load_15_reg_1918),
    .R3_ap_vld(R3_ap_vld),
    .R4(reg_load_16_reg_1923),
    .R4_ap_vld(R4_ap_vld),
    .R5(reg_load_17_reg_1928),
    .R5_ap_vld(R5_ap_vld),
    .R6(reg_r_q0),
    .R6_ap_vld(R6_ap_vld),
    .R7(reg_r_q1),
    .R7_ap_vld(R7_ap_vld),
    .N(N),
    .N_ap_vld(N_ap_vld),
    .Z(Z),
    .Z_ap_vld(Z_ap_vld),
    .P(P),
    .P_ap_vld(P_ap_vld),
    .n1(n1),
    .n1_ap_vld(n1_ap_vld),
    .p1(p1),
    .p1_ap_vld(p1_ap_vld),
    .z1(z1),
    .z1_ap_vld(z1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        PC_assign_10_reg_749 <= reg_879;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        PC_assign_10_reg_749 <= add_ln101_reg_1857;
    end else if ((((1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd2)) | ((1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd10)))) begin
        PC_assign_10_reg_749 <= reg_855;
    end else if (((1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd6))) begin
        PC_assign_10_reg_749 <= add_ln164_reg_1804;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        PC_assign_10_reg_749 <= add_ln186_reg_1765;
    end else if (((1'b1 == ap_CS_fsm_state1) & ((trunc_ln_fu_905_p4 == 4'd8) | ((trunc_ln_fu_905_p4 == 4'd13) | (trunc_ln_fu_905_p4 == 4'd15))))) begin
        PC_assign_10_reg_749 <= PC;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        PC_assign_10_reg_749 <= add_ln207_reg_1754;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        PC_assign_10_reg_749 <= add_ln214_reg_1738;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        PC_assign_10_reg_749 <= grp_fu_838_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state4) & (grp_fu_813_p3 == 1'd1)))) begin
        PC_assign_10_reg_749 <= PC_read_reg_1589;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        n_r <= storemerge9_reg_547;
    end else if (((1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd2))) begin
        n_r <= storemerge24_reg_613;
    end else if (((1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd10))) begin
        n_r <= ap_phi_mux_storemerge19_phi_fu_595_p4;
    end else if (((1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd6))) begin
        n_r <= ap_phi_mux_storemerge14_phi_fu_573_p4;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        n_r <= storemerge30_reg_635;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        n_r <= storemerge36_reg_657;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        n_r <= storemerge43_reg_679;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        p_r <= storemerge7_reg_558;
    end else if (((1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd2))) begin
        p_r <= storemerge22_reg_624;
    end else if (((1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd10))) begin
        p_r <= ap_phi_mux_storemerge17_phi_fu_606_p4;
    end else if (((1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd6))) begin
        p_r <= ap_phi_mux_storemerge12_phi_fu_584_p4;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        p_r <= storemerge28_reg_646;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        p_r <= storemerge34_reg_668;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        p_r <= storemerge41_reg_690;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        phi_ln272_reg_701 <= reg_r_q1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_fu_813_p3 == 1'd1))) begin
        phi_ln272_reg_701 <= add_ln272_1_fu_1044_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        phi_ln272_reg_701 <= reg_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        phi_ln272_reg_701 <= add_ln272_fu_1036_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        reg_861 <= reg_r_q0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_861 <= reg_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        reg_868 <= reg_r_q1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_868 <= reg_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((trunc_ln_reg_1640 == 4'd6)) begin
        if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
            storemerge12_reg_580 <= 1'd0;
        end else if (((icmp_ln170_reg_1809 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
            storemerge12_reg_580 <= icmp_ln174_reg_1813;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((trunc_ln_reg_1640 == 4'd6)) begin
        if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
            storemerge14_reg_569 <= 1'd0;
        end else if (((icmp_ln170_reg_1809 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
            storemerge14_reg_569 <= xor_ln174_fu_1263_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((trunc_ln_reg_1640 == 4'd10)) begin
        if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
            storemerge17_reg_602 <= 1'd0;
        end else if (((icmp_ln148_reg_1819 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
            storemerge17_reg_602 <= icmp_ln152_reg_1823;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((trunc_ln_reg_1640 == 4'd10)) begin
        if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
            storemerge19_reg_591 <= 1'd0;
        end else if (((icmp_ln148_reg_1819 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
            storemerge19_reg_591 <= xor_ln152_fu_1287_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        storemerge22_reg_624 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        storemerge22_reg_624 <= icmp_ln131_reg_1841;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        storemerge24_reg_613 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        storemerge24_reg_613 <= xor_ln131_fu_1385_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        if ((icmp_ln106_fu_1407_p2 == 1'd1)) begin
            storemerge28_reg_646 <= 1'd0;
        end else if ((icmp_ln106_fu_1407_p2 == 1'd0)) begin
            storemerge28_reg_646 <= icmp_ln110_fu_1413_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        if ((icmp_ln106_fu_1407_p2 == 1'd1)) begin
            storemerge30_reg_635 <= 1'd0;
        end else if ((icmp_ln106_fu_1407_p2 == 1'd0)) begin
            storemerge30_reg_635 <= xor_ln110_fu_1425_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd5))) begin
        if ((icmp_ln85_fu_1509_p2 == 1'd1)) begin
            storemerge34_reg_668 <= 1'd0;
        end else if ((icmp_ln85_fu_1509_p2 == 1'd0)) begin
            storemerge34_reg_668 <= icmp_ln89_fu_1514_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd5))) begin
        if ((icmp_ln85_fu_1509_p2 == 1'd1)) begin
            storemerge36_reg_657 <= 1'd0;
        end else if ((icmp_ln85_fu_1509_p2 == 1'd0)) begin
            storemerge36_reg_657 <= xor_ln89_fu_1525_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd1))) begin
        if ((icmp_ln57_fu_1537_p2 == 1'd1)) begin
            storemerge41_reg_690 <= 1'd0;
        end else if ((icmp_ln57_fu_1537_p2 == 1'd0)) begin
            storemerge41_reg_690 <= icmp_ln61_fu_1542_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd1))) begin
        if ((icmp_ln57_fu_1537_p2 == 1'd1)) begin
            storemerge43_reg_679 <= 1'd0;
        end else if ((icmp_ln57_fu_1537_p2 == 1'd0)) begin
            storemerge43_reg_679 <= xor_ln61_fu_1553_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((icmp_ln191_fu_1151_p2 == 1'd1)) begin
            storemerge7_reg_558 <= 1'd0;
        end else if ((icmp_ln191_fu_1151_p2 == 1'd0)) begin
            storemerge7_reg_558 <= icmp_ln195_fu_1157_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((icmp_ln191_fu_1151_p2 == 1'd1)) begin
            storemerge9_reg_547 <= 1'd0;
        end else if ((icmp_ln191_fu_1151_p2 == 1'd0)) begin
            storemerge9_reg_547 <= xor_ln195_fu_1169_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln191_fu_1151_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        z_r <= 1'd1;
    end else if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd10))) begin
        z_r <= 1'd1;
    end else if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd6))) begin
        z_r <= 1'd1;
    end else if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        z_r <= 1'd1;
    end else if (((icmp_ln106_fu_1407_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        z_r <= 1'd1;
    end else if (((icmp_ln57_fu_1537_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd1))) begin
        z_r <= 1'd1;
    end else if (((icmp_ln85_fu_1509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd5))) begin
        z_r <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state26) | ((icmp_ln57_fu_1537_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd1)) | ((icmp_ln85_fu_1509_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd5)) | ((icmp_ln106_fu_1407_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28)) | ((icmp_ln148_reg_1819 == 1'd0) & (1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd10)) | ((icmp_ln170_reg_1809 == 1'd0) & (1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd6)) | ((icmp_ln191_fu_1151_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18)))) begin
        z_r <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        IR_read_reg_1602 <= IR;
        PC_read_reg_1589 <= PC;
        pc_offset6_reg_1618 <= pc_offset6_fu_889_p1;
        pc_offset9_reg_1624 <= pc_offset9_fu_897_p1;
        trunc_ln1_1_reg_1613 <= trunc_ln1_1_fu_885_p1;
        trunc_ln1_5_reg_1634 <= trunc_ln1_5_fu_901_p1;
        trunc_ln_reg_1640 <= {{IR[15:12]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        add_ln101_reg_1857 <= grp_fu_838_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        add_ln164_reg_1804 <= grp_fu_838_p2;
        icmp_ln148_reg_1819 <= grp_fu_843_p2;
        icmp_ln152_reg_1823 <= grp_fu_849_p2;
        icmp_ln170_reg_1809 <= grp_fu_843_p2;
        icmp_ln174_reg_1813 <= grp_fu_849_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        add_ln168_reg_1784 <= add_ln168_fu_1196_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln186_reg_1765 <= grp_fu_838_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln207_reg_1754 <= grp_fu_838_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln214_reg_1738 <= grp_fu_838_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln225_reg_1728 <= add_ln225_fu_1066_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        add_ln52_reg_1881 <= add_ln52_fu_1502_p2;
        and_ln80_reg_1875 <= and_ln80_fu_1472_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        icmp_ln131_reg_1841 <= grp_fu_849_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        or_ln1_1_reg_1829 <= or_ln1_1_fu_1338_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd2)) | ((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd10)))) begin
        reg_855 <= grp_fu_807_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state21) & (trunc_ln_reg_1640 == 4'd10)) | ((1'b1 == ap_CS_fsm_state21) & (trunc_ln_reg_1640 == 4'd6)))) begin
        reg_875 <= {{IR_read_reg_1602[11:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd1)) | ((1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd5)))) begin
        reg_879 <= grp_fu_838_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        reg_load_14_reg_1913 <= reg_r_q0;
        reg_load_15_reg_1918 <= reg_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        reg_load_16_reg_1923 <= reg_r_q0;
        reg_load_17_reg_1928 <= reg_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_3_reg_1677 <= IR_read_reg_1602[32'd11];
        tmp_4_reg_1683 <= IR_read_reg_1602[32'd10];
        tmp_5_reg_1689 <= IR_read_reg_1602[32'd9];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln17_reg_1700 <= {{IR_read_reg_1602[8:6]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        N_ap_vld = 1'b1;
    end else begin
        N_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        PC_out_ap_vld = 1'b1;
    end else begin
        PC_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        P_ap_vld = 1'b1;
    end else begin
        P_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        R0_ap_vld = 1'b1;
    end else begin
        R0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        R1_ap_vld = 1'b1;
    end else begin
        R1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        R2_ap_vld = 1'b1;
    end else begin
        R2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        R3_ap_vld = 1'b1;
    end else begin
        R3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        R4_ap_vld = 1'b1;
    end else begin
        R4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        R5_ap_vld = 1'b1;
    end else begin
        R5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        R6_ap_vld = 1'b1;
    end else begin
        R6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        R7_ap_vld = 1'b1;
    end else begin
        R7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Z_ap_vld = 1'b1;
    end else begin
        Z_ap_vld = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln170_reg_1809 == 1'd0) & (1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd6))) begin
        ap_phi_mux_storemerge12_phi_fu_584_p4 = icmp_ln174_reg_1813;
    end else begin
        ap_phi_mux_storemerge12_phi_fu_584_p4 = storemerge12_reg_580;
    end
end

always @ (*) begin
    if (((icmp_ln170_reg_1809 == 1'd0) & (1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd6))) begin
        ap_phi_mux_storemerge14_phi_fu_573_p4 = xor_ln174_fu_1263_p2;
    end else begin
        ap_phi_mux_storemerge14_phi_fu_573_p4 = storemerge14_reg_569;
    end
end

always @ (*) begin
    if (((icmp_ln148_reg_1819 == 1'd0) & (1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd10))) begin
        ap_phi_mux_storemerge17_phi_fu_606_p4 = icmp_ln152_reg_1823;
    end else begin
        ap_phi_mux_storemerge17_phi_fu_606_p4 = storemerge17_reg_602;
    end
end

always @ (*) begin
    if (((icmp_ln148_reg_1819 == 1'd0) & (1'b1 == ap_CS_fsm_state23) & (trunc_ln_reg_1640 == 4'd10))) begin
        ap_phi_mux_storemerge19_phi_fu_595_p4 = xor_ln152_fu_1287_p2;
    end else begin
        ap_phi_mux_storemerge19_phi_fu_595_p4 = storemerge19_reg_591;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        if ((or_ln1_1_reg_1829 == 1'd0)) begin
            ap_phi_mux_storemerge_phi_fu_788_p4 = PC_assign_10_reg_749;
        end else if ((or_ln1_1_reg_1829 == 1'd1)) begin
            ap_phi_mux_storemerge_phi_fu_788_p4 = phi_ln272_reg_701;
        end else begin
            ap_phi_mux_storemerge_phi_fu_788_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_788_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        memory_address0 = zext_ln125_2_fu_1363_p1;
    end else if (((1'b1 == ap_CS_fsm_state21) & (trunc_ln_reg_1640 == 4'd10))) begin
        memory_address0 = sext_ln146_fu_1230_p1;
    end else if (((1'b1 == ap_CS_fsm_state21) & (trunc_ln_reg_1640 == 4'd6))) begin
        memory_address0 = zext_ln168_2_fu_1226_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        memory_address0 = zext_ln146_2_fu_1221_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        memory_address0 = zext_ln210_2_fu_1132_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        memory_address0 = sext_ln217_fu_1104_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        memory_address0 = zext_ln217_2_fu_1099_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        memory_address0 = zext_ln225_2_fu_1072_p1;
    end else begin
        memory_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state13) | ((1'b1 == ap_CS_fsm_state21) & (trunc_ln_reg_1640 == 4'd10)) | ((1'b1 == ap_CS_fsm_state21) & (trunc_ln_reg_1640 == 4'd6)))) begin
        memory_ce0 = 1'b1;
    end else begin
        memory_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        memory_d0 = reg_r_q0;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state16))) begin
        memory_d0 = reg_r_q1;
    end else begin
        memory_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14))) begin
        memory_we0 = 1'b1;
    end else begin
        memory_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        n1_ap_vld = 1'b1;
    end else begin
        n1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p1_ap_vld = 1'b1;
    end else begin
        p1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        reg_r_address0 = 3'd6;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        reg_r_address0 = 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        reg_r_address0 = 3'd2;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        reg_r_address0 = 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state30) & (trunc_ln_reg_1640 == 4'd1))) begin
        reg_r_address0 = zext_ln52_1_fu_1489_p1;
    end else if (((1'b1 == ap_CS_fsm_state30) & (trunc_ln_reg_1640 == 4'd5))) begin
        reg_r_address0 = zext_ln80_1_fu_1459_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        reg_r_address0 = zext_ln104_fu_1390_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        reg_r_address0 = zext_ln125_fu_1368_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        reg_r_address0 = zext_ln189_fu_1146_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        reg_r_address0 = zext_ln217_fu_1079_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        reg_r_address0 = zext_ln230_fu_1053_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd1))) begin
        reg_r_address0 = zext_ln55_fu_940_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd5))) begin
        reg_r_address0 = zext_ln83_fu_930_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd6))) begin
        reg_r_address0 = zext_ln168_fu_920_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd7))) begin
        reg_r_address0 = zext_ln225_1_fu_915_p1;
    end else begin
        reg_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        reg_r_address1 = 3'd5;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        reg_r_address1 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        reg_r_address1 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        reg_r_address1 = zext_ln104_1_fu_1402_p1;
    end else if (((1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd10))) begin
        reg_r_address1 = zext_ln146_fu_1246_p1;
    end else if (((1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd6))) begin
        reg_r_address1 = zext_ln168_1_fu_1235_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        reg_r_address1 = zext_ln210_fu_1109_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        reg_r_address1 = zext_ln225_fu_1061_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        reg_r_address1 = zext_ln240_fu_1049_p1;
    end else if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_r_address1 = 3'd7;
    end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd1))) begin
        reg_r_address1 = zext_ln52_fu_935_p1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd5))) begin
        reg_r_address1 = zext_ln80_fu_925_p1;
    end else begin
        reg_r_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state35) | ((1'b1 == ap_CS_fsm_state30) & (trunc_ln_reg_1640 == 4'd1)) | ((1'b1 == ap_CS_fsm_state30) & (trunc_ln_reg_1640 == 4'd5)) | ((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd1)) | ((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd5)) | ((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd6)) | ((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd7)))) begin
        reg_r_ce0 = 1'b1;
    end else begin
        reg_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state35) | ((1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd10)) | ((1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd6)) | ((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd1)) | ((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd5)))) begin
        reg_r_ce1 = 1'b1;
    end else begin
        reg_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) & (trunc_ln_reg_1640 == 4'd1))) begin
        reg_r_d0 = add_ln52_fu_1502_p2;
    end else if (((1'b1 == ap_CS_fsm_state30) & (trunc_ln_reg_1640 == 4'd5))) begin
        reg_r_d0 = and_ln80_fu_1472_p2;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        reg_r_d0 = memory_q0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        reg_r_d0 = add_ln189_fu_1140_p2;
    end else begin
        reg_r_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        reg_r_d1 = xor_ln104_fu_1395_p2;
    end else if ((((1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd10)) | ((1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd6)))) begin
        reg_r_d1 = memory_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_r_d1 = PC_read_reg_1589;
    end else begin
        reg_r_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state18) | ((1'b1 == ap_CS_fsm_state30) & (trunc_ln_reg_1640 == 4'd1)) | ((1'b1 == ap_CS_fsm_state30) & (trunc_ln_reg_1640 == 4'd5)))) begin
        reg_r_we0 = 1'b1;
    end else begin
        reg_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd10)) | ((1'b1 == ap_CS_fsm_state22) & (trunc_ln_reg_1640 == 4'd6)))) begin
        reg_r_we1 = 1'b1;
    end else begin
        reg_r_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        z1_ap_vld = 1'b1;
    end else begin
        z1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & ((trunc_ln_fu_905_p4 == 4'd1) | (trunc_ln_fu_905_p4 == 4'd5)))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd9))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd2))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else if (((1'b1 == ap_CS_fsm_state1) & ((trunc_ln_fu_905_p4 == 4'd8) | ((trunc_ln_fu_905_p4 == 4'd13) | (trunc_ln_fu_905_p4 == 4'd15))))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else if (((1'b1 == ap_CS_fsm_state1) & ((trunc_ln_fu_905_p4 == 4'd6) | (trunc_ln_fu_905_p4 == 4'd10)))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd14))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd3))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd7))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd12))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((1'b1 == ap_CS_fsm_state1) & (trunc_ln_fu_905_p4 == 4'd4))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_fu_813_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((grp_fu_843_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((1'b1 == ap_CS_fsm_state31) & (trunc_ln_reg_1640 == 4'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign N = and_ln248_fu_975_p2;

assign P = and_ln249_fu_989_p2;

assign Z = and_ln250_fu_1003_p2;

assign add_ln125_1_fu_1357_p2 = (zext_ln125_1_fu_1353_p1 + reg_855);

assign add_ln125_fu_1347_p2 = (zext_ln32_fu_1344_p1 + 10'd1);

assign add_ln146_1_fu_1215_p2 = (zext_ln146_1_fu_1211_p1 + reg_855);

assign add_ln146_fu_1205_p2 = (zext_ln32_1_fu_1202_p1 + 10'd1);

assign add_ln168_fu_1196_p2 = (reg_r_q0 + zext_ln34_fu_1193_p1);

assign add_ln189_fu_1140_p2 = (add_ln186_reg_1765 + zext_ln189_1_fu_1137_p1);

assign add_ln210_1_fu_1127_p2 = (zext_ln210_1_fu_1123_p1 + add_ln207_reg_1754);

assign add_ln210_fu_1117_p2 = (zext_ln32_2_fu_1114_p1 + 10'd1);

assign add_ln217_1_fu_1094_p2 = (zext_ln217_1_fu_1090_p1 + add_ln214_reg_1738);

assign add_ln217_fu_1084_p2 = (zext_ln32_3_fu_1076_p1 + 10'd1);

assign add_ln225_fu_1066_p2 = (reg_r_q0 + zext_ln34_1_fu_1058_p1);

assign add_ln272_1_fu_1044_p2 = (zext_ln237_fu_1041_p1 + PC_read_reg_1589);

assign add_ln272_fu_1036_p2 = (zext_ln272_fu_1032_p1 + PC_read_reg_1589);

assign add_ln52_fu_1502_p2 = (reg_r_q1 + select_ln51_fu_1494_p3);

assign and_ln248_fu_975_p2 = (tmp_3_reg_1677 & n_r);

assign and_ln249_fu_989_p2 = (tmp_5_reg_1689 & p_r);

assign and_ln250_fu_1003_p2 = (z_r & tmp_4_reg_1683);

assign and_ln80_fu_1472_p2 = (select_ln79_fu_1464_p3 & reg_r_q1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_797_p4 = {{IR[8:6]}};

assign grp_fu_807_p2 = (PC + 16'd1);

assign grp_fu_813_p3 = IR_read_reg_1602[32'd11];

assign grp_fu_820_p4 = {{IR_read_reg_1602[8:6]}};

assign grp_fu_829_p4 = {{IR_read_reg_1602[11:9]}};

assign grp_fu_838_p2 = (PC_read_reg_1589 + 16'd1);

assign grp_fu_843_p2 = ((memory_q0 == 16'd0) ? 1'b1 : 1'b0);

assign grp_fu_849_p2 = (($signed(memory_q0) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_1407_p2 = ((reg_r_q0 == 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_1413_p2 = (($signed(reg_r_q0) < $signed(16'd65535)) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_1151_p2 = ((add_ln189_fu_1140_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln195_fu_1157_p2 = (($signed(add_ln189_fu_1140_p2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1_1_fu_1322_p2 = ((trunc_ln_reg_1640 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln1_2_fu_1333_p2 = ((trunc_ln_reg_1640 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln1_fu_1317_p2 = ((trunc_ln_reg_1640 == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_1537_p2 = ((add_ln52_reg_1881 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_1542_p2 = (($signed(add_ln52_reg_1881) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_1509_p2 = ((and_ln80_reg_1875 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_1514_p2 = (($signed(and_ln80_reg_1875) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign n1 = tmp_3_reg_1677;

assign or_ln1_1_fu_1338_p2 = (or_ln1_fu_1327_p2 | icmp_ln1_2_fu_1333_p2);

assign or_ln1_fu_1327_p2 = (icmp_ln1_fu_1317_p2 | icmp_ln1_1_fu_1322_p2);

assign or_ln251_1_fu_1019_p2 = (or_ln251_fu_1013_p2 | and_ln248_fu_975_p2);

assign or_ln251_fu_1013_p2 = (and_ln250_fu_1003_p2 | and_ln249_fu_989_p2);

assign p1 = tmp_5_reg_1689;

assign pc_offset6_fu_889_p1 = IR[5:0];

assign pc_offset9_fu_897_p1 = IR[8:0];

assign select_ln272_fu_1025_p3 = ((or_ln251_1_fu_1019_p2[0:0] == 1'b1) ? pc_offset9_reg_1624 : 9'd1);

assign select_ln51_fu_1494_p3 = ((tmp_fu_1482_p3[0:0] == 1'b1) ? zext_ln47_fu_1479_p1 : reg_r_q0);

assign select_ln79_fu_1464_p3 = ((tmp_1_fu_1452_p3[0:0] == 1'b1) ? zext_ln75_fu_1449_p1 : reg_r_q0);

assign sext_ln146_fu_1230_p1 = $signed(memory_q0);

assign sext_ln217_fu_1104_p0 = memory_q0;

assign sext_ln217_fu_1104_p1 = sext_ln217_fu_1104_p0;

assign tmp_1_fu_1452_p3 = IR_read_reg_1602[32'd5];

assign tmp_fu_1482_p3 = IR_read_reg_1602[32'd5];

assign trunc_ln1_1_fu_885_p1 = IR[10:0];

assign trunc_ln1_3_fu_893_p1 = IR[2:0];

assign trunc_ln1_5_fu_901_p1 = IR[4:0];

assign trunc_ln_fu_905_p4 = {{IR[15:12]}};

assign xor_ln104_fu_1395_p2 = (reg_r_q0 ^ 16'd65535);

assign xor_ln110_fu_1425_p2 = (icmp_ln110_fu_1413_p2 ^ 1'd1);

assign xor_ln131_fu_1385_p2 = (icmp_ln131_reg_1841 ^ 1'd1);

assign xor_ln152_fu_1287_p2 = (icmp_ln152_reg_1823 ^ 1'd1);

assign xor_ln174_fu_1263_p2 = (icmp_ln174_reg_1813 ^ 1'd1);

assign xor_ln195_fu_1169_p2 = (icmp_ln195_fu_1157_p2 ^ 1'd1);

assign xor_ln61_fu_1553_p2 = (icmp_ln61_fu_1542_p2 ^ 1'd1);

assign xor_ln89_fu_1525_p2 = (icmp_ln89_fu_1514_p2 ^ 1'd1);

assign z1 = tmp_4_reg_1683;

assign zext_ln104_1_fu_1402_p1 = grp_fu_829_p4;

assign zext_ln104_fu_1390_p1 = grp_fu_820_p4;

assign zext_ln125_1_fu_1353_p1 = add_ln125_fu_1347_p2;

assign zext_ln125_2_fu_1363_p1 = add_ln125_1_fu_1357_p2;

assign zext_ln125_fu_1368_p1 = grp_fu_829_p4;

assign zext_ln146_1_fu_1211_p1 = add_ln146_fu_1205_p2;

assign zext_ln146_2_fu_1221_p1 = add_ln146_1_fu_1215_p2;

assign zext_ln146_fu_1246_p1 = reg_875;

assign zext_ln168_1_fu_1235_p1 = reg_875;

assign zext_ln168_2_fu_1226_p1 = add_ln168_reg_1784;

assign zext_ln168_fu_920_p1 = grp_fu_797_p4;

assign zext_ln189_1_fu_1137_p1 = pc_offset9_reg_1624;

assign zext_ln189_fu_1146_p1 = grp_fu_829_p4;

assign zext_ln210_1_fu_1123_p1 = add_ln210_fu_1117_p2;

assign zext_ln210_2_fu_1132_p1 = add_ln210_1_fu_1127_p2;

assign zext_ln210_fu_1109_p1 = grp_fu_829_p4;

assign zext_ln217_1_fu_1090_p1 = add_ln217_fu_1084_p2;

assign zext_ln217_2_fu_1099_p1 = add_ln217_1_fu_1094_p2;

assign zext_ln217_fu_1079_p1 = grp_fu_829_p4;

assign zext_ln225_1_fu_915_p1 = grp_fu_797_p4;

assign zext_ln225_2_fu_1072_p1 = add_ln225_reg_1728;

assign zext_ln225_fu_1061_p1 = grp_fu_829_p4;

assign zext_ln230_fu_1053_p1 = grp_fu_820_p4;

assign zext_ln237_fu_1041_p1 = trunc_ln1_1_reg_1613;

assign zext_ln240_fu_1049_p1 = trunc_ln17_reg_1700;

assign zext_ln272_fu_1032_p1 = select_ln272_fu_1025_p3;

assign zext_ln32_1_fu_1202_p1 = pc_offset9_reg_1624;

assign zext_ln32_2_fu_1114_p1 = pc_offset9_reg_1624;

assign zext_ln32_3_fu_1076_p1 = pc_offset9_reg_1624;

assign zext_ln32_fu_1344_p1 = pc_offset9_reg_1624;

assign zext_ln34_1_fu_1058_p1 = pc_offset6_reg_1618;

assign zext_ln34_fu_1193_p1 = pc_offset6_reg_1618;

assign zext_ln47_fu_1479_p1 = trunc_ln1_5_reg_1634;

assign zext_ln52_1_fu_1489_p1 = grp_fu_829_p4;

assign zext_ln52_fu_935_p1 = grp_fu_797_p4;

assign zext_ln55_fu_940_p1 = trunc_ln1_3_fu_893_p1;

assign zext_ln75_fu_1449_p1 = trunc_ln1_5_reg_1634;

assign zext_ln80_1_fu_1459_p1 = grp_fu_829_p4;

assign zext_ln80_fu_925_p1 = grp_fu_797_p4;

assign zext_ln83_fu_930_p1 = trunc_ln1_3_fu_893_p1;

endmodule //lc3
